// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_RegQotPush.proto

package Qot_RegQotPush

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2S struct {
	SecurityList         []*Security `protobuf:"bytes,1,rep,name=securityList" json:"securityList,omitempty"`
	SubTypeList          []int32     `protobuf:"varint,2,rep,name=subTypeList" json:"subTypeList,omitempty"`
	RehabTypeList        []int32     `protobuf:"varint,3,rep,name=rehabTypeList" json:"rehabTypeList,omitempty"`
	IsRegOrUnReg         *bool       `protobuf:"varint,4,req,name=isRegOrUnReg" json:"isRegOrUnReg,omitempty"`
	IsFirstPush          *bool       `protobuf:"varint,5,opt,name=isFirstPush" json:"isFirstPush,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee73aa5f53fad1, []int{0}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetSecurityList() []*Security {
	if m != nil {
		return m.SecurityList
	}
	return nil
}

func (m *C2S) GetSubTypeList() []int32 {
	if m != nil {
		return m.SubTypeList
	}
	return nil
}

func (m *C2S) GetRehabTypeList() []int32 {
	if m != nil {
		return m.RehabTypeList
	}
	return nil
}

func (m *C2S) GetIsRegOrUnReg() bool {
	if m != nil && m.IsRegOrUnReg != nil {
		return *m.IsRegOrUnReg
	}
	return false
}

func (m *C2S) GetIsFirstPush() bool {
	if m != nil && m.IsFirstPush != nil {
		return *m.IsFirstPush
	}
	return false
}

type S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee73aa5f53fad1, []int{1}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee73aa5f53fad1, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee73aa5f53fad1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Qot_RegQotPush.C2S")
	proto.RegisterType((*S2C)(nil), "Qot_RegQotPush.S2C")
	proto.RegisterType((*Request)(nil), "Qot_RegQotPush.Request")
	proto.RegisterType((*Response)(nil), "Qot_RegQotPush.Response")
}

func init() { proto.RegisterFile("Qot_RegQotPush.proto", fileDescriptor_a9ee73aa5f53fad1) }

var fileDescriptor_a9ee73aa5f53fad1 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xd9, 0xa4, 0xf9, 0xda, 0x6f, 0x5a, 0x45, 0xd6, 0x22, 0x4b, 0x0f, 0xb2, 0x04, 0x85,
	0xbd, 0x58, 0xca, 0xe2, 0x41, 0xbc, 0x06, 0x3c, 0x29, 0xda, 0x89, 0x9e, 0x45, 0xeb, 0x90, 0xe6,
	0xd0, 0x6e, 0xdd, 0xd9, 0x1c, 0x7a, 0xf6, 0xf7, 0xf9, 0x9f, 0x24, 0xb1, 0xc5, 0x44, 0x3c, 0xce,
	0xf3, 0xbc, 0x2f, 0x79, 0xb3, 0x30, 0x9e, 0xbb, 0xf0, 0x8c, 0x54, 0xcc, 0x5d, 0x78, 0xa8, 0x78,
	0x39, 0xdd, 0x78, 0x17, 0x9c, 0x3c, 0xec, 0xd2, 0xc9, 0x28, 0x73, 0xab, 0x95, 0x5b, 0x7f, 0xdb,
	0xc9, 0x51, 0x6d, 0xdb, 0x24, 0xfd, 0x14, 0x10, 0x67, 0x36, 0x97, 0x57, 0x30, 0x62, 0x5a, 0x54,
	0xbe, 0x0c, 0xdb, 0xdb, 0x92, 0x83, 0x12, 0x3a, 0x36, 0x43, 0x3b, 0x9e, 0xb6, 0x0a, 0xf9, 0xce,
	0x63, 0x27, 0x29, 0x35, 0x0c, 0xb9, 0x7a, 0x7d, 0xdc, 0x6e, 0xa8, 0x29, 0x46, 0x3a, 0x36, 0x09,
	0xb6, 0x91, 0x3c, 0x83, 0x03, 0x4f, 0xcb, 0x97, 0x9f, 0x4c, 0xdc, 0x64, 0xba, 0x50, 0xa6, 0x30,
	0x2a, 0x19, 0xa9, 0xb8, 0xf7, 0x4f, 0x6b, 0xa4, 0x42, 0xf5, 0x74, 0x64, 0x06, 0xd8, 0x61, 0xf5,
	0xb7, 0x4a, 0xbe, 0x29, 0x3d, 0x37, 0x3f, 0xa7, 0x12, 0x2d, 0xcc, 0x00, 0xdb, 0x28, 0x4d, 0x20,
	0xce, 0x6d, 0x96, 0xce, 0xa0, 0x8f, 0xf4, 0x5e, 0x11, 0x07, 0x79, 0x0e, 0xf1, 0xc2, 0xb2, 0x12,
	0x3a, 0x32, 0x43, 0x7b, 0x3c, 0xfd, 0xf5, 0x6a, 0x99, 0xcd, 0xb1, 0xf6, 0xe9, 0x87, 0x80, 0x01,
	0x12, 0x6f, 0xdc, 0x9a, 0x49, 0x9e, 0x42, 0xdf, 0x53, 0xa8, 0xa7, 0x35, 0xbd, 0xe4, 0xba, 0x77,
	0x71, 0x39, 0x9b, 0xe1, 0x1e, 0xca, 0x13, 0xf8, 0xe7, 0x29, 0xdc, 0x71, 0xa1, 0x22, 0x2d, 0xcc,
	0x7f, 0xdc, 0x5d, 0x52, 0x41, 0x9f, 0xbc, 0xcf, 0xdc, 0x1b, 0xa9, 0x58, 0x0b, 0x93, 0xe0, 0xfe,
	0xac, 0x57, 0xb0, 0x5d, 0xa8, 0x9e, 0x16, 0x7f, 0xad, 0xc8, 0x6d, 0x86, 0xb5, 0xff, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x1c, 0xd9, 0x7d, 0x93, 0xd5, 0x01, 0x00, 0x00,
}
