// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_Notify.proto

package Trd_Notify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S2C struct {
	Header               *TrdHeader `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Type                 *int32     `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f4a9e49dd36ac1, []int{0}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetHeader() *TrdHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *S2C) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type Response struct {
	//以下3个字段每条协议都有，注释说明在InitConnect.proto中
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f4a9e49dd36ac1, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*S2C)(nil), "Trd_Notify.S2C")
	proto.RegisterType((*Response)(nil), "Trd_Notify.Response")
}

func init() { proto.RegisterFile("Trd_Notify.proto", fileDescriptor_55f4a9e49dd36ac1) }

var fileDescriptor_55f4a9e49dd36ac1 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0x47, 0x65, 0x27, 0x69, 0xe1, 0x8a, 0x04, 0x3a, 0x09, 0x64, 0x75, 0x40, 0xa6, 0x93, 0x97,
	0x46, 0x95, 0xc5, 0xc4, 0xea, 0xa5, 0x0b, 0x0c, 0x6e, 0x76, 0x84, 0xf0, 0xf1, 0x67, 0x68, 0x1c,
	0x9d, 0xbd, 0x64, 0xe2, 0xab, 0xa3, 0x84, 0x44, 0x64, 0xf3, 0xef, 0xbd, 0x27, 0x4b, 0x07, 0x37,
	0x0d, 0x87, 0xd7, 0x97, 0x98, 0xbf, 0x3f, 0xfa, 0xba, 0xe3, 0x98, 0x23, 0xc2, 0x3f, 0xd9, 0x5e,
	0xb9, 0x78, 0x3e, 0xc7, 0xf6, 0xcf, 0x6c, 0xc7, 0x76, 0x49, 0x76, 0x47, 0x28, 0x4e, 0xd6, 0xe1,
	0x1e, 0x56, 0x5f, 0xf4, 0x16, 0x88, 0x95, 0xd0, 0xd2, 0x6c, 0xec, 0x6d, 0xbd, 0x28, 0x1b, 0x0e,
	0xc7, 0x51, 0xfa, 0x29, 0x42, 0x84, 0x32, 0xf7, 0x1d, 0x29, 0xa9, 0xa5, 0xa9, 0xfc, 0xf8, 0xde,
	0xfd, 0xc0, 0x85, 0xa7, 0xd4, 0xc5, 0x36, 0x11, 0xde, 0xc3, 0x9a, 0x29, 0x37, 0x43, 0x32, 0xfc,
	0x57, 0x3d, 0x95, 0xfb, 0xc7, 0xc3, 0xc1, 0xcf, 0x10, 0xef, 0x60, 0xc5, 0x94, 0x9f, 0xd3, 0xa7,
	0x92, 0x5a, 0x98, 0x4b, 0x3f, 0x2d, 0x54, 0xb0, 0x26, 0x66, 0x17, 0x03, 0xa9, 0x42, 0x0b, 0x53,
	0xf9, 0x79, 0xe2, 0x03, 0x14, 0xc9, 0xbe, 0xab, 0x52, 0x0b, 0xb3, 0xb1, 0xd7, 0xf5, 0xe2, 0xe6,
	0x93, 0x75, 0x7e, 0x70, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0xc8, 0xe6, 0xf7, 0x09, 0x01,
	0x00, 0x00,
}
