// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_GetHistoryKLPoints.proto

package Qot_GetHistoryKLPoints

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//当请求时间点数据为空时，如何返回数据
type NoDataMode int32

const (
	NoDataMode_NoDataMode_Null     NoDataMode = 0
	NoDataMode_NoDataMode_Forward  NoDataMode = 1
	NoDataMode_NoDataMode_Backward NoDataMode = 2
)

var NoDataMode_name = map[int32]string{
	0: "NoDataMode_Null",
	1: "NoDataMode_Forward",
	2: "NoDataMode_Backward",
}

var NoDataMode_value = map[string]int32{
	"NoDataMode_Null":     0,
	"NoDataMode_Forward":  1,
	"NoDataMode_Backward": 2,
}

func (x NoDataMode) Enum() *NoDataMode {
	p := new(NoDataMode)
	*p = x
	return p
}

func (x NoDataMode) String() string {
	return proto.EnumName(NoDataMode_name, int32(x))
}

func (x *NoDataMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NoDataMode_value, data, "NoDataMode")
	if err != nil {
		return err
	}
	*x = NoDataMode(value)
	return nil
}

func (NoDataMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{0}
}

//这个时间点返回数据的状态以及来源
type DataStatus int32

const (
	DataStatus_DataStatus_Null     DataStatus = 0
	DataStatus_DataStatus_Current  DataStatus = 1
	DataStatus_DataStatus_Previous DataStatus = 2
	DataStatus_DataStatus_Back     DataStatus = 3
)

var DataStatus_name = map[int32]string{
	0: "DataStatus_Null",
	1: "DataStatus_Current",
	2: "DataStatus_Previous",
	3: "DataStatus_Back",
}

var DataStatus_value = map[string]int32{
	"DataStatus_Null":     0,
	"DataStatus_Current":  1,
	"DataStatus_Previous": 2,
	"DataStatus_Back":     3,
}

func (x DataStatus) Enum() *DataStatus {
	p := new(DataStatus)
	*p = x
	return p
}

func (x DataStatus) String() string {
	return proto.EnumName(DataStatus_name, int32(x))
}

func (x *DataStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DataStatus_value, data, "DataStatus")
	if err != nil {
		return err
	}
	*x = DataStatus(value)
	return nil
}

func (DataStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{1}
}

type C2S struct {
	RehabType            *int32      `protobuf:"varint,1,req,name=rehabType" json:"rehabType,omitempty"`
	KlType               *int32      `protobuf:"varint,2,req,name=klType" json:"klType,omitempty"`
	NoDataMode           *int32      `protobuf:"varint,3,req,name=noDataMode" json:"noDataMode,omitempty"`
	SecurityList         []*Security `protobuf:"bytes,4,rep,name=securityList" json:"securityList,omitempty"`
	TimeList             []string    `protobuf:"bytes,5,rep,name=timeList" json:"timeList,omitempty"`
	MaxReqSecurityNum    *int32      `protobuf:"varint,6,opt,name=maxReqSecurityNum" json:"maxReqSecurityNum,omitempty"`
	NeedKLFieldsFlag     *int64      `protobuf:"varint,7,opt,name=needKLFieldsFlag" json:"needKLFieldsFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{0}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetRehabType() int32 {
	if m != nil && m.RehabType != nil {
		return *m.RehabType
	}
	return 0
}

func (m *C2S) GetKlType() int32 {
	if m != nil && m.KlType != nil {
		return *m.KlType
	}
	return 0
}

func (m *C2S) GetNoDataMode() int32 {
	if m != nil && m.NoDataMode != nil {
		return *m.NoDataMode
	}
	return 0
}

func (m *C2S) GetSecurityList() []*Security {
	if m != nil {
		return m.SecurityList
	}
	return nil
}

func (m *C2S) GetTimeList() []string {
	if m != nil {
		return m.TimeList
	}
	return nil
}

func (m *C2S) GetMaxReqSecurityNum() int32 {
	if m != nil && m.MaxReqSecurityNum != nil {
		return *m.MaxReqSecurityNum
	}
	return 0
}

func (m *C2S) GetNeedKLFieldsFlag() int64 {
	if m != nil && m.NeedKLFieldsFlag != nil {
		return *m.NeedKLFieldsFlag
	}
	return 0
}

type HistoryPointsKL struct {
	Status               *int32   `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	ReqTime              *string  `protobuf:"bytes,2,req,name=reqTime" json:"reqTime,omitempty"`
	Kl                   *KLine   `protobuf:"bytes,3,req,name=kl" json:"kl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryPointsKL) Reset()         { *m = HistoryPointsKL{} }
func (m *HistoryPointsKL) String() string { return proto.CompactTextString(m) }
func (*HistoryPointsKL) ProtoMessage()    {}
func (*HistoryPointsKL) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{1}
}

func (m *HistoryPointsKL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryPointsKL.Unmarshal(m, b)
}
func (m *HistoryPointsKL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryPointsKL.Marshal(b, m, deterministic)
}
func (m *HistoryPointsKL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryPointsKL.Merge(m, src)
}
func (m *HistoryPointsKL) XXX_Size() int {
	return xxx_messageInfo_HistoryPointsKL.Size(m)
}
func (m *HistoryPointsKL) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryPointsKL.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryPointsKL proto.InternalMessageInfo

func (m *HistoryPointsKL) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *HistoryPointsKL) GetReqTime() string {
	if m != nil && m.ReqTime != nil {
		return *m.ReqTime
	}
	return ""
}

func (m *HistoryPointsKL) GetKl() *KLine {
	if m != nil {
		return m.Kl
	}
	return nil
}

type SecurityHistoryKLPoints struct {
	Security             *Security          `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	KlList               []*HistoryPointsKL `protobuf:"bytes,2,rep,name=klList" json:"klList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SecurityHistoryKLPoints) Reset()         { *m = SecurityHistoryKLPoints{} }
func (m *SecurityHistoryKLPoints) String() string { return proto.CompactTextString(m) }
func (*SecurityHistoryKLPoints) ProtoMessage()    {}
func (*SecurityHistoryKLPoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{2}
}

func (m *SecurityHistoryKLPoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityHistoryKLPoints.Unmarshal(m, b)
}
func (m *SecurityHistoryKLPoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityHistoryKLPoints.Marshal(b, m, deterministic)
}
func (m *SecurityHistoryKLPoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityHistoryKLPoints.Merge(m, src)
}
func (m *SecurityHistoryKLPoints) XXX_Size() int {
	return xxx_messageInfo_SecurityHistoryKLPoints.Size(m)
}
func (m *SecurityHistoryKLPoints) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityHistoryKLPoints.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityHistoryKLPoints proto.InternalMessageInfo

func (m *SecurityHistoryKLPoints) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *SecurityHistoryKLPoints) GetKlList() []*HistoryPointsKL {
	if m != nil {
		return m.KlList
	}
	return nil
}

type S2C struct {
	KlPointList          []*SecurityHistoryKLPoints `protobuf:"bytes,1,rep,name=klPointList" json:"klPointList,omitempty"`
	HasNext              *bool                      `protobuf:"varint,2,opt,name=hasNext" json:"hasNext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{3}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetKlPointList() []*SecurityHistoryKLPoints {
	if m != nil {
		return m.KlPointList
	}
	return nil
}

func (m *S2C) GetHasNext() bool {
	if m != nil && m.HasNext != nil {
		return *m.HasNext
	}
	return false
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad26a2b1eebc2d1d, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterEnum("Qot_GetHistoryKLPoints.NoDataMode", NoDataMode_name, NoDataMode_value)
	proto.RegisterEnum("Qot_GetHistoryKLPoints.DataStatus", DataStatus_name, DataStatus_value)
	proto.RegisterType((*C2S)(nil), "Qot_GetHistoryKLPoints.C2S")
	proto.RegisterType((*HistoryPointsKL)(nil), "Qot_GetHistoryKLPoints.HistoryPointsKL")
	proto.RegisterType((*SecurityHistoryKLPoints)(nil), "Qot_GetHistoryKLPoints.SecurityHistoryKLPoints")
	proto.RegisterType((*S2C)(nil), "Qot_GetHistoryKLPoints.S2C")
	proto.RegisterType((*Request)(nil), "Qot_GetHistoryKLPoints.Request")
	proto.RegisterType((*Response)(nil), "Qot_GetHistoryKLPoints.Response")
}

func init() { proto.RegisterFile("Qot_GetHistoryKLPoints.proto", fileDescriptor_ad26a2b1eebc2d1d) }

var fileDescriptor_ad26a2b1eebc2d1d = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x6f, 0xda, 0x30,
	0x14, 0x5d, 0x92, 0x52, 0xe0, 0x52, 0x89, 0xd4, 0x4c, 0x34, 0x62, 0xd5, 0x94, 0xe5, 0x65, 0x11,
	0x5a, 0x19, 0x8a, 0xf6, 0x50, 0xed, 0x65, 0xd2, 0x32, 0xb1, 0x49, 0x50, 0xd4, 0x3a, 0x7d, 0xaf,
	0x32, 0xf0, 0x68, 0x44, 0x12, 0x83, 0xed, 0x6c, 0xe5, 0x37, 0x74, 0x3f, 0x7a, 0xb2, 0x93, 0x94,
	0x8c, 0x2e, 0x7b, 0x3c, 0xe7, 0x5c, 0xdf, 0x8f, 0xe3, 0x03, 0xe7, 0x37, 0x54, 0xdc, 0x7d, 0x25,
	0xe2, 0x5b, 0xc4, 0x05, 0x65, 0xbb, 0xe9, 0xec, 0x9a, 0x46, 0xa9, 0xe0, 0xa3, 0x0d, 0xa3, 0x82,
	0xa2, 0xfe, 0xbf, 0xd5, 0xc1, 0x89, 0x4f, 0x93, 0x84, 0xa6, 0x79, 0xd5, 0xc0, 0x94, 0x55, 0x55,
	0xc6, 0x79, 0xd4, 0xc1, 0xf0, 0xbd, 0x00, 0x9d, 0x43, 0x9b, 0x91, 0xfb, 0xf0, 0xfb, 0xed, 0x6e,
	0x43, 0x2c, 0xcd, 0xd6, 0xdd, 0x06, 0xde, 0x13, 0xa8, 0x0f, 0xc7, 0xeb, 0x58, 0x49, 0xba, 0x92,
	0x0a, 0x84, 0x5e, 0x03, 0xa4, 0xf4, 0x4b, 0x28, 0xc2, 0x2b, 0xba, 0x24, 0x96, 0xa1, 0xb4, 0x0a,
	0x83, 0x2e, 0xe1, 0x84, 0x93, 0x45, 0xc6, 0x22, 0xb1, 0x9b, 0x45, 0x5c, 0x58, 0x47, 0xb6, 0xe1,
	0x76, 0xbc, 0x97, 0xa3, 0xca, 0x1a, 0x41, 0xa1, 0xe3, 0xbf, 0x2a, 0xd1, 0x00, 0x5a, 0x22, 0x4a,
	0x88, 0x7a, 0xd5, 0xb0, 0x0d, 0xb7, 0x8d, 0x9f, 0x30, 0x7a, 0x07, 0xa7, 0x49, 0xf8, 0x80, 0xc9,
	0xb6, 0x7c, 0x3b, 0xcf, 0x12, 0xeb, 0xd8, 0xd6, 0xdc, 0x06, 0x7e, 0x2e, 0xa0, 0x21, 0x98, 0x29,
	0x21, 0xcb, 0xe9, 0x6c, 0x12, 0x91, 0x78, 0xc9, 0x27, 0x71, 0xb8, 0xb2, 0x9a, 0xb6, 0xe6, 0x1a,
	0xf8, 0x19, 0xef, 0xfc, 0x80, 0x6e, 0x61, 0x60, 0x6e, 0xdf, 0x74, 0x26, 0x4f, 0xe7, 0x22, 0x14,
	0x19, 0x2f, 0x5c, 0x29, 0x10, 0xb2, 0xa0, 0xc9, 0xc8, 0xf6, 0x36, 0x4a, 0x72, 0x4f, 0xda, 0xb8,
	0x84, 0xe8, 0x0d, 0xe8, 0xeb, 0x58, 0x99, 0xd1, 0xf1, 0x4e, 0xab, 0xa7, 0x4e, 0x67, 0x51, 0x4a,
	0xb0, 0xbe, 0x8e, 0x9d, 0xdf, 0x1a, 0x9c, 0x95, 0x3b, 0x1e, 0xfc, 0x18, 0x1a, 0x43, 0xab, 0x74,
	0x42, 0x8d, 0xac, 0xf3, 0xeb, 0xa9, 0x0a, 0x7d, 0x92, 0xbf, 0xa3, 0x9c, 0xd2, 0x95, 0xbf, 0x6f,
	0x47, 0x35, 0x51, 0x39, 0xb8, 0x0d, 0x17, 0xcf, 0x1c, 0x06, 0x46, 0xe0, 0xf9, 0xe8, 0x06, 0x3a,
	0xeb, 0x58, 0x89, 0xaa, 0x99, 0xa6, 0x9a, 0xbd, 0xaf, 0x6b, 0x56, 0xb3, 0x3f, 0xae, 0xf6, 0x90,
	0x2e, 0xdd, 0x87, 0x7c, 0x4e, 0x1e, 0xe4, 0x6e, 0x9a, 0xdb, 0xc2, 0x25, 0x74, 0x2e, 0xa1, 0x89,
	0xc9, 0x36, 0x23, 0x5c, 0xa0, 0x0b, 0x30, 0x16, 0x1e, 0x2f, 0x8e, 0x7d, 0x55, 0x37, 0xcf, 0xf7,
	0x02, 0x2c, 0xeb, 0x9c, 0x47, 0x0d, 0x5a, 0x98, 0xf0, 0x0d, 0x4d, 0xb9, 0x4c, 0x60, 0x93, 0x11,
	0xb1, 0x4f, 0xed, 0xc7, 0xa3, 0x8b, 0x0f, 0xe3, 0x31, 0x2e, 0x49, 0xf9, 0x7d, 0x8c, 0x88, 0x2b,
	0xbe, 0x52, 0xf3, 0xdb, 0xb8, 0x40, 0x72, 0x31, 0xc2, 0x98, 0x9f, 0xc7, 0x56, 0x26, 0xa7, 0x84,
	0x72, 0x1b, 0xee, 0x2d, 0xac, 0x23, 0x5b, 0xfb, 0xdf, 0x36, 0x81, 0xe7, 0x63, 0x59, 0x37, 0xc4,
	0x00, 0xf3, 0x7d, 0xe0, 0x7b, 0xd0, 0xdd, 0xa3, 0xbb, 0x79, 0x16, 0xc7, 0xe6, 0x0b, 0xd4, 0x07,
	0x54, 0x21, 0x27, 0x94, 0xfd, 0x0a, 0xd9, 0xd2, 0xd4, 0xd0, 0x19, 0xf4, 0x2a, 0xfc, 0xe7, 0x70,
	0xb1, 0x56, 0x82, 0x3e, 0x5c, 0x01, 0x48, 0x3a, 0xc8, 0x93, 0xd6, 0x83, 0xee, 0x1e, 0x55, 0x7a,
	0x56, 0x48, 0x3f, 0x63, 0x8c, 0xa4, 0x22, 0xef, 0x59, 0xe1, 0xaf, 0x19, 0xf9, 0x19, 0xd1, 0x8c,
	0x9b, 0xfa, 0x41, 0x17, 0x39, 0xcc, 0x34, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x5a, 0x7c,
	0x02, 0x54, 0x04, 0x00, 0x00,
}
