// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trd_Common.proto

package Trd_Common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//交易环境
type TrdEnv int32

const (
	TrdEnv_TrdEnv_Simulate TrdEnv = 0
	TrdEnv_TrdEnv_Real     TrdEnv = 1
)

var TrdEnv_name = map[int32]string{
	0: "TrdEnv_Simulate",
	1: "TrdEnv_Real",
}

var TrdEnv_value = map[string]int32{
	"TrdEnv_Simulate": 0,
	"TrdEnv_Real":     1,
}

func (x TrdEnv) Enum() *TrdEnv {
	p := new(TrdEnv)
	*p = x
	return p
}

func (x TrdEnv) String() string {
	return proto.EnumName(TrdEnv_name, int32(x))
}

func (x *TrdEnv) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrdEnv_value, data, "TrdEnv")
	if err != nil {
		return err
	}
	*x = TrdEnv(value)
	return nil
}

func (TrdEnv) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{0}
}

//交易市场，是大的市场，不是具体品种
type TrdMarket int32

const (
	TrdMarket_TrdMarket_Unknown TrdMarket = 0
	TrdMarket_TrdMarket_HK      TrdMarket = 1
	TrdMarket_TrdMarket_US      TrdMarket = 2
	TrdMarket_TrdMarket_CN      TrdMarket = 3
	TrdMarket_TrdMarket_HKCC    TrdMarket = 4
)

var TrdMarket_name = map[int32]string{
	0: "TrdMarket_Unknown",
	1: "TrdMarket_HK",
	2: "TrdMarket_US",
	3: "TrdMarket_CN",
	4: "TrdMarket_HKCC",
}

var TrdMarket_value = map[string]int32{
	"TrdMarket_Unknown": 0,
	"TrdMarket_HK":      1,
	"TrdMarket_US":      2,
	"TrdMarket_CN":      3,
	"TrdMarket_HKCC":    4,
}

func (x TrdMarket) Enum() *TrdMarket {
	p := new(TrdMarket)
	*p = x
	return p
}

func (x TrdMarket) String() string {
	return proto.EnumName(TrdMarket_name, int32(x))
}

func (x *TrdMarket) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrdMarket_value, data, "TrdMarket")
	if err != nil {
		return err
	}
	*x = TrdMarket(value)
	return nil
}

func (TrdMarket) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{1}
}

//可交易证券所属市场，目前主要是区分A股的沪市和深市，香港和美国暂不需要细分
type TrdSecMarket int32

const (
	TrdSecMarket_TrdSecMarket_Unknown TrdSecMarket = 0
	TrdSecMarket_TrdSecMarket_HK      TrdSecMarket = 1
	TrdSecMarket_TrdSecMarket_US      TrdSecMarket = 2
	TrdSecMarket_TrdSecMarket_CN_SH   TrdSecMarket = 31
	TrdSecMarket_TrdSecMarket_CN_SZ   TrdSecMarket = 32
)

var TrdSecMarket_name = map[int32]string{
	0:  "TrdSecMarket_Unknown",
	1:  "TrdSecMarket_HK",
	2:  "TrdSecMarket_US",
	31: "TrdSecMarket_CN_SH",
	32: "TrdSecMarket_CN_SZ",
}

var TrdSecMarket_value = map[string]int32{
	"TrdSecMarket_Unknown": 0,
	"TrdSecMarket_HK":      1,
	"TrdSecMarket_US":      2,
	"TrdSecMarket_CN_SH":   31,
	"TrdSecMarket_CN_SZ":   32,
}

func (x TrdSecMarket) Enum() *TrdSecMarket {
	p := new(TrdSecMarket)
	*p = x
	return p
}

func (x TrdSecMarket) String() string {
	return proto.EnumName(TrdSecMarket_name, int32(x))
}

func (x *TrdSecMarket) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrdSecMarket_value, data, "TrdSecMarket")
	if err != nil {
		return err
	}
	*x = TrdSecMarket(value)
	return nil
}

func (TrdSecMarket) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{2}
}

//交易方向
type TrdSide int32

const (
	//客户端下单只传Buy或Sell即可，SellShort是美股订单时服务器返回有此方向，BuyBack目前不存在，但也不排除服务器会传
	TrdSide_TrdSide_Unknown   TrdSide = 0
	TrdSide_TrdSide_Buy       TrdSide = 1
	TrdSide_TrdSide_Sell      TrdSide = 2
	TrdSide_TrdSide_SellShort TrdSide = 3
	TrdSide_TrdSide_BuyBack   TrdSide = 4
)

var TrdSide_name = map[int32]string{
	0: "TrdSide_Unknown",
	1: "TrdSide_Buy",
	2: "TrdSide_Sell",
	3: "TrdSide_SellShort",
	4: "TrdSide_BuyBack",
}

var TrdSide_value = map[string]int32{
	"TrdSide_Unknown":   0,
	"TrdSide_Buy":       1,
	"TrdSide_Sell":      2,
	"TrdSide_SellShort": 3,
	"TrdSide_BuyBack":   4,
}

func (x TrdSide) Enum() *TrdSide {
	p := new(TrdSide)
	*p = x
	return p
}

func (x TrdSide) String() string {
	return proto.EnumName(TrdSide_name, int32(x))
}

func (x *TrdSide) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TrdSide_value, data, "TrdSide")
	if err != nil {
		return err
	}
	*x = TrdSide(value)
	return nil
}

func (TrdSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{3}
}

//订单类型
type OrderType int32

const (
	OrderType_OrderType_Unknown       OrderType = 0
	OrderType_OrderType_Normal        OrderType = 1
	OrderType_OrderType_Market        OrderType = 2
	OrderType_OrderType_AbsoluteLimit OrderType = 5
	OrderType_OrderType_Auction       OrderType = 6
	OrderType_OrderType_AuctionLimit  OrderType = 7
	OrderType_OrderType_SpecialLimit  OrderType = 8
)

var OrderType_name = map[int32]string{
	0: "OrderType_Unknown",
	1: "OrderType_Normal",
	2: "OrderType_Market",
	5: "OrderType_AbsoluteLimit",
	6: "OrderType_Auction",
	7: "OrderType_AuctionLimit",
	8: "OrderType_SpecialLimit",
}

var OrderType_value = map[string]int32{
	"OrderType_Unknown":       0,
	"OrderType_Normal":        1,
	"OrderType_Market":        2,
	"OrderType_AbsoluteLimit": 5,
	"OrderType_Auction":       6,
	"OrderType_AuctionLimit":  7,
	"OrderType_SpecialLimit":  8,
}

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (x *OrderType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OrderType_value, data, "OrderType")
	if err != nil {
		return err
	}
	*x = OrderType(value)
	return nil
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{4}
}

//订单状态
type OrderStatus int32

const (
	OrderStatus_OrderStatus_Unsubmitted     OrderStatus = 0
	OrderStatus_OrderStatus_Unknown         OrderStatus = -1
	OrderStatus_OrderStatus_WaitingSubmit   OrderStatus = 1
	OrderStatus_OrderStatus_Submitting      OrderStatus = 2
	OrderStatus_OrderStatus_SubmitFailed    OrderStatus = 3
	OrderStatus_OrderStatus_TimeOut         OrderStatus = 4
	OrderStatus_OrderStatus_Submitted       OrderStatus = 5
	OrderStatus_OrderStatus_Filled_Part     OrderStatus = 10
	OrderStatus_OrderStatus_Filled_All      OrderStatus = 11
	OrderStatus_OrderStatus_Cancelling_Part OrderStatus = 12
	OrderStatus_OrderStatus_Cancelling_All  OrderStatus = 13
	OrderStatus_OrderStatus_Cancelled_Part  OrderStatus = 14
	OrderStatus_OrderStatus_Cancelled_All   OrderStatus = 15
	OrderStatus_OrderStatus_Failed          OrderStatus = 21
	OrderStatus_OrderStatus_Disabled        OrderStatus = 22
	OrderStatus_OrderStatus_Deleted         OrderStatus = 23
)

var OrderStatus_name = map[int32]string{
	0:  "OrderStatus_Unsubmitted",
	-1: "OrderStatus_Unknown",
	1:  "OrderStatus_WaitingSubmit",
	2:  "OrderStatus_Submitting",
	3:  "OrderStatus_SubmitFailed",
	4:  "OrderStatus_TimeOut",
	5:  "OrderStatus_Submitted",
	10: "OrderStatus_Filled_Part",
	11: "OrderStatus_Filled_All",
	12: "OrderStatus_Cancelling_Part",
	13: "OrderStatus_Cancelling_All",
	14: "OrderStatus_Cancelled_Part",
	15: "OrderStatus_Cancelled_All",
	21: "OrderStatus_Failed",
	22: "OrderStatus_Disabled",
	23: "OrderStatus_Deleted",
}

var OrderStatus_value = map[string]int32{
	"OrderStatus_Unsubmitted":     0,
	"OrderStatus_Unknown":         -1,
	"OrderStatus_WaitingSubmit":   1,
	"OrderStatus_Submitting":      2,
	"OrderStatus_SubmitFailed":    3,
	"OrderStatus_TimeOut":         4,
	"OrderStatus_Submitted":       5,
	"OrderStatus_Filled_Part":     10,
	"OrderStatus_Filled_All":      11,
	"OrderStatus_Cancelling_Part": 12,
	"OrderStatus_Cancelling_All":  13,
	"OrderStatus_Cancelled_Part":  14,
	"OrderStatus_Cancelled_All":   15,
	"OrderStatus_Failed":          21,
	"OrderStatus_Disabled":        22,
	"OrderStatus_Deleted":         23,
}

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (x *OrderStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OrderStatus_value, data, "OrderStatus")
	if err != nil {
		return err
	}
	*x = OrderStatus(value)
	return nil
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{5}
}

//持仓方向类型
type PositionSide int32

const (
	PositionSide_PositionSide_Long    PositionSide = 0
	PositionSide_PositionSide_Unknown PositionSide = -1
	PositionSide_PositionSide_Short   PositionSide = 1
)

var PositionSide_name = map[int32]string{
	0:  "PositionSide_Long",
	-1: "PositionSide_Unknown",
	1:  "PositionSide_Short",
}

var PositionSide_value = map[string]int32{
	"PositionSide_Long":    0,
	"PositionSide_Unknown": -1,
	"PositionSide_Short":   1,
}

func (x PositionSide) Enum() *PositionSide {
	p := new(PositionSide)
	*p = x
	return p
}

func (x PositionSide) String() string {
	return proto.EnumName(PositionSide_name, int32(x))
}

func (x *PositionSide) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PositionSide_value, data, "PositionSide")
	if err != nil {
		return err
	}
	*x = PositionSide(value)
	return nil
}

func (PositionSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{6}
}

//修改订单的操作类型
type ModifyOrderOp int32

const (
	//港股支持全部操作，美股目前仅支持ModifyOrderOp_Normal和ModifyOrderOp_Cancel
	ModifyOrderOp_ModifyOrderOp_Unknown ModifyOrderOp = 0
	ModifyOrderOp_ModifyOrderOp_Normal  ModifyOrderOp = 1
	ModifyOrderOp_ModifyOrderOp_Cancel  ModifyOrderOp = 2
	ModifyOrderOp_ModifyOrderOp_Disable ModifyOrderOp = 3
	ModifyOrderOp_ModifyOrderOp_Enable  ModifyOrderOp = 4
	ModifyOrderOp_ModifyOrderOp_Delete  ModifyOrderOp = 5
)

var ModifyOrderOp_name = map[int32]string{
	0: "ModifyOrderOp_Unknown",
	1: "ModifyOrderOp_Normal",
	2: "ModifyOrderOp_Cancel",
	3: "ModifyOrderOp_Disable",
	4: "ModifyOrderOp_Enable",
	5: "ModifyOrderOp_Delete",
}

var ModifyOrderOp_value = map[string]int32{
	"ModifyOrderOp_Unknown": 0,
	"ModifyOrderOp_Normal":  1,
	"ModifyOrderOp_Cancel":  2,
	"ModifyOrderOp_Disable": 3,
	"ModifyOrderOp_Enable":  4,
	"ModifyOrderOp_Delete":  5,
}

func (x ModifyOrderOp) Enum() *ModifyOrderOp {
	p := new(ModifyOrderOp)
	*p = x
	return p
}

func (x ModifyOrderOp) String() string {
	return proto.EnumName(ModifyOrderOp_name, int32(x))
}

func (x *ModifyOrderOp) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ModifyOrderOp_value, data, "ModifyOrderOp")
	if err != nil {
		return err
	}
	*x = ModifyOrderOp(value)
	return nil
}

func (ModifyOrderOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{7}
}

//需要再次确认订单的原因枚举
type ReconfirmOrderReason int32

const (
	ReconfirmOrderReason_ReconfirmOrderReason_Unknown       ReconfirmOrderReason = 0
	ReconfirmOrderReason_ReconfirmOrderReason_QtyTooLarge   ReconfirmOrderReason = 1
	ReconfirmOrderReason_ReconfirmOrderReason_PriceAbnormal ReconfirmOrderReason = 2
)

var ReconfirmOrderReason_name = map[int32]string{
	0: "ReconfirmOrderReason_Unknown",
	1: "ReconfirmOrderReason_QtyTooLarge",
	2: "ReconfirmOrderReason_PriceAbnormal",
}

var ReconfirmOrderReason_value = map[string]int32{
	"ReconfirmOrderReason_Unknown":       0,
	"ReconfirmOrderReason_QtyTooLarge":   1,
	"ReconfirmOrderReason_PriceAbnormal": 2,
}

func (x ReconfirmOrderReason) Enum() *ReconfirmOrderReason {
	p := new(ReconfirmOrderReason)
	*p = x
	return p
}

func (x ReconfirmOrderReason) String() string {
	return proto.EnumName(ReconfirmOrderReason_name, int32(x))
}

func (x *ReconfirmOrderReason) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReconfirmOrderReason_value, data, "ReconfirmOrderReason")
	if err != nil {
		return err
	}
	*x = ReconfirmOrderReason(value)
	return nil
}

func (ReconfirmOrderReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{8}
}

//交易协议公共参数头
type TrdHeader struct {
	TrdEnv               *int32   `protobuf:"varint,1,req,name=trdEnv" json:"trdEnv,omitempty"`
	AccID                *uint64  `protobuf:"varint,2,req,name=accID" json:"accID,omitempty"`
	TrdMarket            *int32   `protobuf:"varint,3,req,name=trdMarket" json:"trdMarket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrdHeader) Reset()         { *m = TrdHeader{} }
func (m *TrdHeader) String() string { return proto.CompactTextString(m) }
func (*TrdHeader) ProtoMessage()    {}
func (*TrdHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{0}
}

func (m *TrdHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrdHeader.Unmarshal(m, b)
}
func (m *TrdHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrdHeader.Marshal(b, m, deterministic)
}
func (m *TrdHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrdHeader.Merge(m, src)
}
func (m *TrdHeader) XXX_Size() int {
	return xxx_messageInfo_TrdHeader.Size(m)
}
func (m *TrdHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TrdHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TrdHeader proto.InternalMessageInfo

func (m *TrdHeader) GetTrdEnv() int32 {
	if m != nil && m.TrdEnv != nil {
		return *m.TrdEnv
	}
	return 0
}

func (m *TrdHeader) GetAccID() uint64 {
	if m != nil && m.AccID != nil {
		return *m.AccID
	}
	return 0
}

func (m *TrdHeader) GetTrdMarket() int32 {
	if m != nil && m.TrdMarket != nil {
		return *m.TrdMarket
	}
	return 0
}

//交易业务账户结构
type TrdAcc struct {
	TrdEnv               *int32   `protobuf:"varint,1,req,name=trdEnv" json:"trdEnv,omitempty"`
	AccID                *uint64  `protobuf:"varint,2,req,name=accID" json:"accID,omitempty"`
	TrdMarketAuthList    []int32  `protobuf:"varint,3,rep,name=trdMarketAuthList" json:"trdMarketAuthList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrdAcc) Reset()         { *m = TrdAcc{} }
func (m *TrdAcc) String() string { return proto.CompactTextString(m) }
func (*TrdAcc) ProtoMessage()    {}
func (*TrdAcc) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{1}
}

func (m *TrdAcc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrdAcc.Unmarshal(m, b)
}
func (m *TrdAcc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrdAcc.Marshal(b, m, deterministic)
}
func (m *TrdAcc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrdAcc.Merge(m, src)
}
func (m *TrdAcc) XXX_Size() int {
	return xxx_messageInfo_TrdAcc.Size(m)
}
func (m *TrdAcc) XXX_DiscardUnknown() {
	xxx_messageInfo_TrdAcc.DiscardUnknown(m)
}

var xxx_messageInfo_TrdAcc proto.InternalMessageInfo

func (m *TrdAcc) GetTrdEnv() int32 {
	if m != nil && m.TrdEnv != nil {
		return *m.TrdEnv
	}
	return 0
}

func (m *TrdAcc) GetAccID() uint64 {
	if m != nil && m.AccID != nil {
		return *m.AccID
	}
	return 0
}

func (m *TrdAcc) GetTrdMarketAuthList() []int32 {
	if m != nil {
		return m.TrdMarketAuthList
	}
	return nil
}

//账户资金结构
type Funds struct {
	Power                *float64 `protobuf:"fixed64,1,req,name=power" json:"power,omitempty"`
	TotalAssets          *float64 `protobuf:"fixed64,2,req,name=totalAssets" json:"totalAssets,omitempty"`
	Cash                 *float64 `protobuf:"fixed64,3,req,name=cash" json:"cash,omitempty"`
	MarketVal            *float64 `protobuf:"fixed64,4,req,name=marketVal" json:"marketVal,omitempty"`
	FrozenCash           *float64 `protobuf:"fixed64,5,req,name=frozenCash" json:"frozenCash,omitempty"`
	DebtCash             *float64 `protobuf:"fixed64,6,req,name=debtCash" json:"debtCash,omitempty"`
	AvlWithdrawalCash    *float64 `protobuf:"fixed64,7,req,name=avlWithdrawalCash" json:"avlWithdrawalCash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Funds) Reset()         { *m = Funds{} }
func (m *Funds) String() string { return proto.CompactTextString(m) }
func (*Funds) ProtoMessage()    {}
func (*Funds) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{2}
}

func (m *Funds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Funds.Unmarshal(m, b)
}
func (m *Funds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Funds.Marshal(b, m, deterministic)
}
func (m *Funds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Funds.Merge(m, src)
}
func (m *Funds) XXX_Size() int {
	return xxx_messageInfo_Funds.Size(m)
}
func (m *Funds) XXX_DiscardUnknown() {
	xxx_messageInfo_Funds.DiscardUnknown(m)
}

var xxx_messageInfo_Funds proto.InternalMessageInfo

func (m *Funds) GetPower() float64 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Funds) GetTotalAssets() float64 {
	if m != nil && m.TotalAssets != nil {
		return *m.TotalAssets
	}
	return 0
}

func (m *Funds) GetCash() float64 {
	if m != nil && m.Cash != nil {
		return *m.Cash
	}
	return 0
}

func (m *Funds) GetMarketVal() float64 {
	if m != nil && m.MarketVal != nil {
		return *m.MarketVal
	}
	return 0
}

func (m *Funds) GetFrozenCash() float64 {
	if m != nil && m.FrozenCash != nil {
		return *m.FrozenCash
	}
	return 0
}

func (m *Funds) GetDebtCash() float64 {
	if m != nil && m.DebtCash != nil {
		return *m.DebtCash
	}
	return 0
}

func (m *Funds) GetAvlWithdrawalCash() float64 {
	if m != nil && m.AvlWithdrawalCash != nil {
		return *m.AvlWithdrawalCash
	}
	return 0
}

//账户持仓结构
type Position struct {
	PositionID   *uint64  `protobuf:"varint,1,req,name=positionID" json:"positionID,omitempty"`
	PositionSide *int32   `protobuf:"varint,2,req,name=positionSide" json:"positionSide,omitempty"`
	Code         *string  `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	Name         *string  `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	Qty          *float64 `protobuf:"fixed64,5,req,name=qty" json:"qty,omitempty"`
	CanSellQty   *float64 `protobuf:"fixed64,6,req,name=canSellQty" json:"canSellQty,omitempty"`
	Price        *float64 `protobuf:"fixed64,7,req,name=price" json:"price,omitempty"`
	CostPrice    *float64 `protobuf:"fixed64,8,opt,name=costPrice" json:"costPrice,omitempty"`
	Val          *float64 `protobuf:"fixed64,9,req,name=val" json:"val,omitempty"`
	PlVal        *float64 `protobuf:"fixed64,10,req,name=plVal" json:"plVal,omitempty"`
	PlRatio      *float64 `protobuf:"fixed64,11,opt,name=plRatio" json:"plRatio,omitempty"`
	SecMarket    *int32   `protobuf:"varint,12,opt,name=secMarket" json:"secMarket,omitempty"`
	//以下是此持仓今日统计
	TdPlVal              *float64 `protobuf:"fixed64,21,opt,name=td_plVal,json=tdPlVal" json:"td_plVal,omitempty"`
	TdTrdVal             *float64 `protobuf:"fixed64,22,opt,name=td_trdVal,json=tdTrdVal" json:"td_trdVal,omitempty"`
	TdBuyVal             *float64 `protobuf:"fixed64,23,opt,name=td_buyVal,json=tdBuyVal" json:"td_buyVal,omitempty"`
	TdBuyQty             *float64 `protobuf:"fixed64,24,opt,name=td_buyQty,json=tdBuyQty" json:"td_buyQty,omitempty"`
	TdSellVal            *float64 `protobuf:"fixed64,25,opt,name=td_sellVal,json=tdSellVal" json:"td_sellVal,omitempty"`
	TdSellQty            *float64 `protobuf:"fixed64,26,opt,name=td_sellQty,json=tdSellQty" json:"td_sellQty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{3}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetPositionID() uint64 {
	if m != nil && m.PositionID != nil {
		return *m.PositionID
	}
	return 0
}

func (m *Position) GetPositionSide() int32 {
	if m != nil && m.PositionSide != nil {
		return *m.PositionSide
	}
	return 0
}

func (m *Position) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Position) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Position) GetQty() float64 {
	if m != nil && m.Qty != nil {
		return *m.Qty
	}
	return 0
}

func (m *Position) GetCanSellQty() float64 {
	if m != nil && m.CanSellQty != nil {
		return *m.CanSellQty
	}
	return 0
}

func (m *Position) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Position) GetCostPrice() float64 {
	if m != nil && m.CostPrice != nil {
		return *m.CostPrice
	}
	return 0
}

func (m *Position) GetVal() float64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

func (m *Position) GetPlVal() float64 {
	if m != nil && m.PlVal != nil {
		return *m.PlVal
	}
	return 0
}

func (m *Position) GetPlRatio() float64 {
	if m != nil && m.PlRatio != nil {
		return *m.PlRatio
	}
	return 0
}

func (m *Position) GetSecMarket() int32 {
	if m != nil && m.SecMarket != nil {
		return *m.SecMarket
	}
	return 0
}

func (m *Position) GetTdPlVal() float64 {
	if m != nil && m.TdPlVal != nil {
		return *m.TdPlVal
	}
	return 0
}

func (m *Position) GetTdTrdVal() float64 {
	if m != nil && m.TdTrdVal != nil {
		return *m.TdTrdVal
	}
	return 0
}

func (m *Position) GetTdBuyVal() float64 {
	if m != nil && m.TdBuyVal != nil {
		return *m.TdBuyVal
	}
	return 0
}

func (m *Position) GetTdBuyQty() float64 {
	if m != nil && m.TdBuyQty != nil {
		return *m.TdBuyQty
	}
	return 0
}

func (m *Position) GetTdSellVal() float64 {
	if m != nil && m.TdSellVal != nil {
		return *m.TdSellVal
	}
	return 0
}

func (m *Position) GetTdSellQty() float64 {
	if m != nil && m.TdSellQty != nil {
		return *m.TdSellQty
	}
	return 0
}

//订单结构
type Order struct {
	TrdSide              *int32   `protobuf:"varint,1,req,name=trdSide" json:"trdSide,omitempty"`
	OrderType            *int32   `protobuf:"varint,2,req,name=orderType" json:"orderType,omitempty"`
	OrderStatus          *int32   `protobuf:"varint,3,req,name=orderStatus" json:"orderStatus,omitempty"`
	OrderID              *uint64  `protobuf:"varint,4,req,name=orderID" json:"orderID,omitempty"`
	OrderIDEx            *string  `protobuf:"bytes,5,req,name=orderIDEx" json:"orderIDEx,omitempty"`
	Code                 *string  `protobuf:"bytes,6,req,name=code" json:"code,omitempty"`
	Name                 *string  `protobuf:"bytes,7,req,name=name" json:"name,omitempty"`
	Qty                  *float64 `protobuf:"fixed64,8,req,name=qty" json:"qty,omitempty"`
	Price                *float64 `protobuf:"fixed64,9,opt,name=price" json:"price,omitempty"`
	CreateTime           *string  `protobuf:"bytes,10,req,name=createTime" json:"createTime,omitempty"`
	UpdateTime           *string  `protobuf:"bytes,11,req,name=updateTime" json:"updateTime,omitempty"`
	FillQty              *float64 `protobuf:"fixed64,12,opt,name=fillQty" json:"fillQty,omitempty"`
	FillAvgPrice         *float64 `protobuf:"fixed64,13,opt,name=fillAvgPrice" json:"fillAvgPrice,omitempty"`
	LastErrMsg           *string  `protobuf:"bytes,14,opt,name=lastErrMsg" json:"lastErrMsg,omitempty"`
	SecMarket            *int32   `protobuf:"varint,15,opt,name=secMarket" json:"secMarket,omitempty"`
	CreateTimestamp      *float64 `protobuf:"fixed64,16,opt,name=createTimestamp" json:"createTimestamp,omitempty"`
	UpdateTimestamp      *float64 `protobuf:"fixed64,17,opt,name=updateTimestamp" json:"updateTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{4}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetTrdSide() int32 {
	if m != nil && m.TrdSide != nil {
		return *m.TrdSide
	}
	return 0
}

func (m *Order) GetOrderType() int32 {
	if m != nil && m.OrderType != nil {
		return *m.OrderType
	}
	return 0
}

func (m *Order) GetOrderStatus() int32 {
	if m != nil && m.OrderStatus != nil {
		return *m.OrderStatus
	}
	return 0
}

func (m *Order) GetOrderID() uint64 {
	if m != nil && m.OrderID != nil {
		return *m.OrderID
	}
	return 0
}

func (m *Order) GetOrderIDEx() string {
	if m != nil && m.OrderIDEx != nil {
		return *m.OrderIDEx
	}
	return ""
}

func (m *Order) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Order) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Order) GetQty() float64 {
	if m != nil && m.Qty != nil {
		return *m.Qty
	}
	return 0
}

func (m *Order) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Order) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

func (m *Order) GetUpdateTime() string {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return ""
}

func (m *Order) GetFillQty() float64 {
	if m != nil && m.FillQty != nil {
		return *m.FillQty
	}
	return 0
}

func (m *Order) GetFillAvgPrice() float64 {
	if m != nil && m.FillAvgPrice != nil {
		return *m.FillAvgPrice
	}
	return 0
}

func (m *Order) GetLastErrMsg() string {
	if m != nil && m.LastErrMsg != nil {
		return *m.LastErrMsg
	}
	return ""
}

func (m *Order) GetSecMarket() int32 {
	if m != nil && m.SecMarket != nil {
		return *m.SecMarket
	}
	return 0
}

func (m *Order) GetCreateTimestamp() float64 {
	if m != nil && m.CreateTimestamp != nil {
		return *m.CreateTimestamp
	}
	return 0
}

func (m *Order) GetUpdateTimestamp() float64 {
	if m != nil && m.UpdateTimestamp != nil {
		return *m.UpdateTimestamp
	}
	return 0
}

//成交结构
type OrderFill struct {
	TrdSide              *int32   `protobuf:"varint,1,req,name=trdSide" json:"trdSide,omitempty"`
	FillID               *uint64  `protobuf:"varint,2,req,name=fillID" json:"fillID,omitempty"`
	FillIDEx             *string  `protobuf:"bytes,3,req,name=fillIDEx" json:"fillIDEx,omitempty"`
	OrderID              *uint64  `protobuf:"varint,4,opt,name=orderID" json:"orderID,omitempty"`
	OrderIDEx            *string  `protobuf:"bytes,5,opt,name=orderIDEx" json:"orderIDEx,omitempty"`
	Code                 *string  `protobuf:"bytes,6,req,name=code" json:"code,omitempty"`
	Name                 *string  `protobuf:"bytes,7,req,name=name" json:"name,omitempty"`
	Qty                  *float64 `protobuf:"fixed64,8,req,name=qty" json:"qty,omitempty"`
	Price                *float64 `protobuf:"fixed64,9,req,name=price" json:"price,omitempty"`
	CreateTime           *string  `protobuf:"bytes,10,req,name=createTime" json:"createTime,omitempty"`
	CounterBrokerID      *int32   `protobuf:"varint,11,opt,name=counterBrokerID" json:"counterBrokerID,omitempty"`
	CounterBrokerName    *string  `protobuf:"bytes,12,opt,name=counterBrokerName" json:"counterBrokerName,omitempty"`
	SecMarket            *int32   `protobuf:"varint,13,opt,name=secMarket" json:"secMarket,omitempty"`
	CreateTimestamp      *float64 `protobuf:"fixed64,14,opt,name=createTimestamp" json:"createTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderFill) Reset()         { *m = OrderFill{} }
func (m *OrderFill) String() string { return proto.CompactTextString(m) }
func (*OrderFill) ProtoMessage()    {}
func (*OrderFill) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{5}
}

func (m *OrderFill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFill.Unmarshal(m, b)
}
func (m *OrderFill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFill.Marshal(b, m, deterministic)
}
func (m *OrderFill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFill.Merge(m, src)
}
func (m *OrderFill) XXX_Size() int {
	return xxx_messageInfo_OrderFill.Size(m)
}
func (m *OrderFill) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFill.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFill proto.InternalMessageInfo

func (m *OrderFill) GetTrdSide() int32 {
	if m != nil && m.TrdSide != nil {
		return *m.TrdSide
	}
	return 0
}

func (m *OrderFill) GetFillID() uint64 {
	if m != nil && m.FillID != nil {
		return *m.FillID
	}
	return 0
}

func (m *OrderFill) GetFillIDEx() string {
	if m != nil && m.FillIDEx != nil {
		return *m.FillIDEx
	}
	return ""
}

func (m *OrderFill) GetOrderID() uint64 {
	if m != nil && m.OrderID != nil {
		return *m.OrderID
	}
	return 0
}

func (m *OrderFill) GetOrderIDEx() string {
	if m != nil && m.OrderIDEx != nil {
		return *m.OrderIDEx
	}
	return ""
}

func (m *OrderFill) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *OrderFill) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *OrderFill) GetQty() float64 {
	if m != nil && m.Qty != nil {
		return *m.Qty
	}
	return 0
}

func (m *OrderFill) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *OrderFill) GetCreateTime() string {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return ""
}

func (m *OrderFill) GetCounterBrokerID() int32 {
	if m != nil && m.CounterBrokerID != nil {
		return *m.CounterBrokerID
	}
	return 0
}

func (m *OrderFill) GetCounterBrokerName() string {
	if m != nil && m.CounterBrokerName != nil {
		return *m.CounterBrokerName
	}
	return ""
}

func (m *OrderFill) GetSecMarket() int32 {
	if m != nil && m.SecMarket != nil {
		return *m.SecMarket
	}
	return 0
}

func (m *OrderFill) GetCreateTimestamp() float64 {
	if m != nil && m.CreateTimestamp != nil {
		return *m.CreateTimestamp
	}
	return 0
}

//最大可交易数量
type MaxTrdQtys struct {
	//因目前服务器实现的问题，卖空需要先卖掉持仓才能再卖空，是分开两步卖的，买回来同样是逆向两步；而看多的买是可以现金加融资一起一步买的，请注意这个差异
	MaxCashBuy           *float64 `protobuf:"fixed64,1,req,name=maxCashBuy" json:"maxCashBuy,omitempty"`
	MaxCashAndMarginBuy  *float64 `protobuf:"fixed64,2,opt,name=maxCashAndMarginBuy" json:"maxCashAndMarginBuy,omitempty"`
	MaxPositionSell      *float64 `protobuf:"fixed64,3,req,name=maxPositionSell" json:"maxPositionSell,omitempty"`
	MaxSellShort         *float64 `protobuf:"fixed64,4,opt,name=maxSellShort" json:"maxSellShort,omitempty"`
	MaxBuyBack           *float64 `protobuf:"fixed64,5,opt,name=maxBuyBack" json:"maxBuyBack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxTrdQtys) Reset()         { *m = MaxTrdQtys{} }
func (m *MaxTrdQtys) String() string { return proto.CompactTextString(m) }
func (*MaxTrdQtys) ProtoMessage()    {}
func (*MaxTrdQtys) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{6}
}

func (m *MaxTrdQtys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxTrdQtys.Unmarshal(m, b)
}
func (m *MaxTrdQtys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxTrdQtys.Marshal(b, m, deterministic)
}
func (m *MaxTrdQtys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxTrdQtys.Merge(m, src)
}
func (m *MaxTrdQtys) XXX_Size() int {
	return xxx_messageInfo_MaxTrdQtys.Size(m)
}
func (m *MaxTrdQtys) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxTrdQtys.DiscardUnknown(m)
}

var xxx_messageInfo_MaxTrdQtys proto.InternalMessageInfo

func (m *MaxTrdQtys) GetMaxCashBuy() float64 {
	if m != nil && m.MaxCashBuy != nil {
		return *m.MaxCashBuy
	}
	return 0
}

func (m *MaxTrdQtys) GetMaxCashAndMarginBuy() float64 {
	if m != nil && m.MaxCashAndMarginBuy != nil {
		return *m.MaxCashAndMarginBuy
	}
	return 0
}

func (m *MaxTrdQtys) GetMaxPositionSell() float64 {
	if m != nil && m.MaxPositionSell != nil {
		return *m.MaxPositionSell
	}
	return 0
}

func (m *MaxTrdQtys) GetMaxSellShort() float64 {
	if m != nil && m.MaxSellShort != nil {
		return *m.MaxSellShort
	}
	return 0
}

func (m *MaxTrdQtys) GetMaxBuyBack() float64 {
	if m != nil && m.MaxBuyBack != nil {
		return *m.MaxBuyBack
	}
	return 0
}

//过滤条件，条件组合是"与"不是"或"，用于获取订单、成交、持仓等时二次过滤
type TrdFilterConditions struct {
	CodeList             []string `protobuf:"bytes,1,rep,name=codeList" json:"codeList,omitempty"`
	IdList               []uint64 `protobuf:"varint,2,rep,name=idList" json:"idList,omitempty"`
	BeginTime            *string  `protobuf:"bytes,3,opt,name=beginTime" json:"beginTime,omitempty"`
	EndTime              *string  `protobuf:"bytes,4,opt,name=endTime" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrdFilterConditions) Reset()         { *m = TrdFilterConditions{} }
func (m *TrdFilterConditions) String() string { return proto.CompactTextString(m) }
func (*TrdFilterConditions) ProtoMessage()    {}
func (*TrdFilterConditions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ead9262a0b33, []int{7}
}

func (m *TrdFilterConditions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrdFilterConditions.Unmarshal(m, b)
}
func (m *TrdFilterConditions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrdFilterConditions.Marshal(b, m, deterministic)
}
func (m *TrdFilterConditions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrdFilterConditions.Merge(m, src)
}
func (m *TrdFilterConditions) XXX_Size() int {
	return xxx_messageInfo_TrdFilterConditions.Size(m)
}
func (m *TrdFilterConditions) XXX_DiscardUnknown() {
	xxx_messageInfo_TrdFilterConditions.DiscardUnknown(m)
}

var xxx_messageInfo_TrdFilterConditions proto.InternalMessageInfo

func (m *TrdFilterConditions) GetCodeList() []string {
	if m != nil {
		return m.CodeList
	}
	return nil
}

func (m *TrdFilterConditions) GetIdList() []uint64 {
	if m != nil {
		return m.IdList
	}
	return nil
}

func (m *TrdFilterConditions) GetBeginTime() string {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return ""
}

func (m *TrdFilterConditions) GetEndTime() string {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return ""
}

func init() {
	proto.RegisterEnum("Trd_Common.TrdEnv", TrdEnv_name, TrdEnv_value)
	proto.RegisterEnum("Trd_Common.TrdMarket", TrdMarket_name, TrdMarket_value)
	proto.RegisterEnum("Trd_Common.TrdSecMarket", TrdSecMarket_name, TrdSecMarket_value)
	proto.RegisterEnum("Trd_Common.TrdSide", TrdSide_name, TrdSide_value)
	proto.RegisterEnum("Trd_Common.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("Trd_Common.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("Trd_Common.PositionSide", PositionSide_name, PositionSide_value)
	proto.RegisterEnum("Trd_Common.ModifyOrderOp", ModifyOrderOp_name, ModifyOrderOp_value)
	proto.RegisterEnum("Trd_Common.ReconfirmOrderReason", ReconfirmOrderReason_name, ReconfirmOrderReason_value)
	proto.RegisterType((*TrdHeader)(nil), "Trd_Common.TrdHeader")
	proto.RegisterType((*TrdAcc)(nil), "Trd_Common.TrdAcc")
	proto.RegisterType((*Funds)(nil), "Trd_Common.Funds")
	proto.RegisterType((*Position)(nil), "Trd_Common.Position")
	proto.RegisterType((*Order)(nil), "Trd_Common.Order")
	proto.RegisterType((*OrderFill)(nil), "Trd_Common.OrderFill")
	proto.RegisterType((*MaxTrdQtys)(nil), "Trd_Common.MaxTrdQtys")
	proto.RegisterType((*TrdFilterConditions)(nil), "Trd_Common.TrdFilterConditions")
}

func init() { proto.RegisterFile("Trd_Common.proto", fileDescriptor_0949ead9262a0b33) }

var fileDescriptor_0949ead9262a0b33 = []byte{
	// 1417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x6e, 0x23, 0x45,
	0x14, 0x4d, 0xfb, 0x91, 0xc4, 0x37, 0x4e, 0x52, 0xa9, 0xbc, 0x9c, 0xcc, 0xcb, 0x58, 0x08, 0x45,
	0x16, 0x1a, 0xb1, 0x05, 0xc7, 0x49, 0x34, 0x11, 0x79, 0xb6, 0x3d, 0x8c, 0xc4, 0x8f, 0x29, 0xbb,
	0x2a, 0x4e, 0x2b, 0xfd, 0x30, 0xdd, 0xe5, 0x4c, 0xcc, 0x1f, 0x7c, 0xb0, 0x0f, 0x16, 0xc0, 0x06,
	0x58, 0x03, 0x3b, 0x40, 0xec, 0x80, 0x0d, 0xf0, 0x05, 0xba, 0xb7, 0xda, 0xfd, 0xb0, 0x3d, 0xa3,
	0xe1, 0x83, 0xfe, 0xaa, 0x7b, 0xce, 0xad, 0xfb, 0xae, 0xaa, 0x06, 0xd6, 0x0d, 0x65, 0xaf, 0x1d,
	0x78, 0x5e, 0xe0, 0xbf, 0x1e, 0x85, 0x81, 0x0e, 0x38, 0xa4, 0xc8, 0x61, 0x35, 0xcb, 0x34, 0xde,
	0x41, 0xa5, 0x1b, 0xca, 0x37, 0x4a, 0x48, 0x15, 0xf2, 0x3d, 0x58, 0xd6, 0xa1, 0x3c, 0xf5, 0x1f,
	0x6b, 0x56, 0xbd, 0x70, 0x54, 0xb6, 0x63, 0x89, 0xef, 0x40, 0x59, 0x0c, 0x06, 0xe7, 0x27, 0xb5,
	0x42, 0xbd, 0x70, 0x54, 0xb2, 0x8d, 0xc0, 0x9f, 0x43, 0x45, 0x87, 0xf2, 0x52, 0x84, 0x0f, 0x4a,
	0xd7, 0x8a, 0xb4, 0x21, 0x05, 0x1a, 0x12, 0x96, 0xbb, 0xa1, 0x6c, 0x0d, 0x06, 0xff, 0xd1, 0xea,
	0x97, 0xb0, 0x95, 0x18, 0x69, 0x8d, 0xf5, 0xfd, 0x85, 0x13, 0xa1, 0xf5, 0xe2, 0x51, 0xd9, 0x9e,
	0x27, 0x1a, 0x7f, 0x58, 0x50, 0x3e, 0x1b, 0xfb, 0x32, 0x42, 0x6b, 0xa3, 0xe0, 0xbd, 0x0a, 0xc9,
	0x89, 0x65, 0x1b, 0x81, 0xd7, 0x61, 0x4d, 0x07, 0x5a, 0xb8, 0xad, 0x28, 0x52, 0x3a, 0x22, 0x4f,
	0x96, 0x9d, 0x85, 0x38, 0x87, 0xd2, 0x40, 0x44, 0xf7, 0x94, 0x80, 0x65, 0xd3, 0x1a, 0x33, 0xf3,
	0xc8, 0xcf, 0x37, 0xc2, 0xad, 0x95, 0x88, 0x48, 0x01, 0xfe, 0x12, 0xe0, 0x2e, 0x0c, 0x7e, 0x50,
	0x7e, 0x1b, 0xf7, 0x95, 0x89, 0xce, 0x20, 0xfc, 0x10, 0x56, 0xa5, 0xea, 0x6b, 0x62, 0x97, 0x89,
	0x4d, 0x64, 0xcc, 0x4e, 0x3c, 0xba, 0xef, 0x1c, 0x7d, 0x2f, 0x43, 0xf1, 0x5e, 0xb8, 0xa4, 0xb4,
	0x42, 0x4a, 0xf3, 0x44, 0xe3, 0xaf, 0x22, 0xac, 0xde, 0x04, 0x91, 0xa3, 0x9d, 0xc0, 0x47, 0xb7,
	0xa3, 0x78, 0x7d, 0x7e, 0x42, 0x59, 0x96, 0xec, 0x0c, 0xc2, 0x1b, 0x50, 0x9d, 0x4a, 0x1d, 0x47,
	0x2a, 0xca, 0xb5, 0x6c, 0xe7, 0x30, 0x4a, 0x36, 0x90, 0x8a, 0x92, 0xad, 0xd8, 0xb4, 0x46, 0xcc,
	0x17, 0x9e, 0xa2, 0x3c, 0x2b, 0x36, 0xad, 0x39, 0x83, 0xe2, 0xf7, 0x7a, 0x12, 0xe7, 0x86, 0x4b,
	0xf4, 0x3e, 0x10, 0x7e, 0x47, 0xb9, 0xee, 0xad, 0x9e, 0xc4, 0x69, 0x65, 0x10, 0x2a, 0x7f, 0xe8,
	0x0c, 0x54, 0x9c, 0x8c, 0x11, 0xb0, 0x90, 0x83, 0x20, 0xd2, 0x37, 0xc4, 0xac, 0xd6, 0x2d, 0x2c,
	0x64, 0x02, 0xa0, 0x97, 0x47, 0xe1, 0xd6, 0x2a, 0xc6, 0xcb, 0xa3, 0x70, 0xc9, 0x8a, 0x8b, 0x45,
	0x87, 0xd8, 0x0a, 0x0a, 0xbc, 0x06, 0x2b, 0x23, 0xd7, 0x16, 0xda, 0x09, 0x6a, 0x6b, 0x64, 0x63,
	0x2a, 0xa2, 0xfd, 0x48, 0x0d, 0xe2, 0x11, 0xac, 0xd6, 0x2d, 0x1c, 0xc1, 0x04, 0xe0, 0x07, 0xb0,
	0xaa, 0x65, 0xcf, 0x18, 0xdc, 0x35, 0x1b, 0xb5, 0xbc, 0x21, 0x93, 0xcf, 0xa0, 0xa2, 0x65, 0x4f,
	0x87, 0x12, 0xb9, 0x3d, 0xe2, 0x56, 0xb5, 0xec, 0x92, 0x1c, 0x93, 0xfd, 0xf1, 0x04, 0xc9, 0xfd,
	0x29, 0x79, 0x4c, 0x72, 0x4a, 0x62, 0x1d, 0x6a, 0x19, 0x12, 0xab, 0xf0, 0x02, 0x40, 0xcb, 0x5e,
	0xa4, 0x5c, 0xf2, 0x79, 0x60, 0x12, 0xd6, 0xb2, 0x63, 0x80, 0x0c, 0x8d, 0x9b, 0x0f, 0xb3, 0xf4,
	0xad, 0x9e, 0x34, 0xfe, 0x2e, 0x42, 0xf9, 0x3a, 0xc4, 0x83, 0x58, 0x83, 0x15, 0x1d, 0x4a, 0x6a,
	0xa3, 0x39, 0x33, 0x53, 0x11, 0x33, 0x0e, 0x50, 0xa5, 0x3b, 0x19, 0x4d, 0x5b, 0x9c, 0x02, 0x38,
	0xee, 0x24, 0x74, 0xb4, 0xd0, 0xe3, 0x28, 0x3e, 0x94, 0x59, 0x08, 0x2d, 0x93, 0x78, 0x7e, 0x42,
	0x0d, 0x2f, 0xd9, 0x53, 0x31, 0xb1, 0x7c, 0x7e, 0x72, 0xfa, 0x44, 0x9d, 0xaf, 0xd8, 0x29, 0x90,
	0x4c, 0xce, 0xf2, 0x82, 0xc9, 0x59, 0x99, 0x9f, 0x9c, 0xd5, 0x74, 0x72, 0x92, 0xc9, 0xa8, 0x50,
	0xbe, 0xf1, 0x64, 0xe0, 0x3c, 0x85, 0x4a, 0x68, 0xd5, 0x75, 0x3c, 0x45, 0xed, 0xae, 0xd8, 0x19,
	0x04, 0xf9, 0xf1, 0x48, 0x4e, 0xf9, 0x35, 0xc3, 0xa7, 0x08, 0xe6, 0x71, 0xe7, 0x98, 0x3a, 0x56,
	0x4d, 0x6b, 0x63, 0x11, 0xcf, 0x01, 0x2e, 0x5b, 0x8f, 0x43, 0x33, 0x76, 0xeb, 0x44, 0xe7, 0x30,
	0xb4, 0xee, 0x8a, 0x48, 0x9f, 0x86, 0xe1, 0x65, 0x34, 0xac, 0x6d, 0xd4, 0x2d, 0xb4, 0x9e, 0x22,
	0xf9, 0xb9, 0xda, 0x9c, 0x9d, 0xab, 0x23, 0xd8, 0x4c, 0x23, 0x8d, 0xb4, 0xf0, 0x46, 0x35, 0x46,
	0x4e, 0x66, 0x61, 0xd4, 0x4c, 0x63, 0x36, 0x9a, 0x5b, 0x46, 0x73, 0x06, 0x6e, 0xfc, 0x52, 0x84,
	0x0a, 0xf5, 0xfe, 0xcc, 0x71, 0xdd, 0x8f, 0xf4, 0x7f, 0x0f, 0x96, 0x31, 0x93, 0xe4, 0xd6, 0x8c,
	0x25, 0xbc, 0x74, 0xcc, 0xea, 0xf4, 0x29, 0x3e, 0xdd, 0x89, 0x9c, 0xef, 0xb9, 0xf5, 0x91, 0x9e,
	0x5b, 0xff, 0x43, 0xcf, 0x0b, 0x9f, 0xde, 0x73, 0xac, 0x6b, 0x30, 0xf6, 0xb5, 0x0a, 0x8f, 0xc3,
	0xe0, 0x81, 0xe2, 0x5d, 0xa3, 0xda, 0xcf, 0xc2, 0x78, 0x8d, 0xe6, 0xa0, 0x2b, 0x0c, 0xa9, 0x4a,
	0xf1, 0xcf, 0x13, 0xf9, 0x6e, 0xae, 0x7f, 0x42, 0x37, 0x37, 0x16, 0x76, 0xb3, 0xf1, 0xbb, 0x05,
	0x70, 0x29, 0x9e, 0xba, 0xa1, 0xbc, 0xd5, 0x93, 0x08, 0xd3, 0xf1, 0xc4, 0x13, 0x5e, 0xd4, 0xc7,
	0xe3, 0x49, 0xfc, 0xec, 0x64, 0x10, 0xfe, 0x15, 0x6c, 0xc7, 0x52, 0xcb, 0xc7, 0x77, 0x6b, 0xe8,
	0xf8, 0xa8, 0x58, 0x20, 0xe3, 0x8b, 0x28, 0x0c, 0xc5, 0x13, 0x4f, 0xd3, 0x1b, 0x1f, 0xaf, 0x85,
	0xf8, 0x59, 0x9a, 0x85, 0x71, 0xc8, 0x3d, 0xf1, 0x84, 0xcb, 0xce, 0x7d, 0x10, 0x6a, 0xea, 0xab,
	0x65, 0xe7, 0xb0, 0x38, 0xbe, 0xe3, 0xf1, 0xe4, 0x58, 0x0c, 0x1e, 0xa8, 0xbb, 0x26, 0xbe, 0x18,
	0x69, 0xfc, 0x68, 0xc1, 0x76, 0x37, 0x94, 0x67, 0x8e, 0xab, 0x55, 0xd8, 0x0e, 0x7c, 0x49, 0xe6,
	0x23, 0x1c, 0x25, 0x6c, 0x35, 0x3d, 0xbc, 0x56, 0xbd, 0x88, 0xa3, 0x34, 0x95, 0x71, 0xfc, 0x1c,
	0x49, 0x4c, 0xa1, 0x5e, 0xc4, 0xf1, 0x33, 0x12, 0x96, 0xb8, 0xaf, 0x86, 0x8e, 0x4f, 0x9d, 0x2d,
	0x9a, 0x41, 0x4a, 0x00, 0x1c, 0x40, 0xe5, 0x4b, 0xe2, 0x4a, 0xc4, 0x4d, 0xc5, 0xe6, 0x6b, 0xfa,
	0x4b, 0xc0, 0xbf, 0x81, 0x6d, 0xd8, 0x34, 0xab, 0x5e, 0xc7, 0xf1, 0xc6, 0xae, 0xd0, 0x8a, 0x2d,
	0xf1, 0x4d, 0x58, 0x8b, 0x41, 0x5b, 0x09, 0x97, 0x59, 0x4d, 0x97, 0x7e, 0x57, 0xe2, 0xce, 0xed,
	0xc2, 0x56, 0x22, 0xf4, 0xde, 0xfa, 0x0f, 0x7e, 0xf0, 0xde, 0x67, 0x4b, 0x9c, 0x41, 0x35, 0x85,
	0xdf, 0x7c, 0xcd, 0xac, 0x3c, 0xf2, 0xb6, 0xc3, 0x0a, 0x79, 0xa4, 0x7d, 0xc5, 0x8a, 0x9c, 0xc3,
	0x46, 0x76, 0x57, 0xbb, 0xcd, 0x4a, 0xcd, 0x9f, 0x2c, 0x52, 0xeb, 0x24, 0xb3, 0x52, 0x83, 0x9d,
	0xac, 0x9c, 0x71, 0x6a, 0xc2, 0x4f, 0x19, 0xf2, 0x3b, 0x0b, 0x92, 0xeb, 0x3d, 0xe0, 0x39, 0xb0,
	0x7d, 0xd5, 0xeb, 0xbc, 0x61, 0xaf, 0x16, 0xe2, 0xdf, 0xb2, 0x7a, 0xd3, 0x83, 0x95, 0x6e, 0x7c,
	0xf8, 0x63, 0x7b, 0x8e, 0x54, 0x19, 0xcf, 0xa6, 0x46, 0x04, 0x1e, 0x8f, 0x27, 0x49, 0xb6, 0x04,
	0xe0, 0x30, 0xb0, 0x42, 0x5c, 0xa8, 0x04, 0xa1, 0xf1, 0x60, 0xc5, 0xac, 0xb9, 0x78, 0x26, 0x58,
	0xa9, 0xf9, 0x9b, 0x15, 0x5f, 0x44, 0xf4, 0xa0, 0xec, 0xc2, 0x56, 0x22, 0x64, 0x7c, 0xee, 0x00,
	0x4b, 0xe1, 0xab, 0x20, 0xf4, 0xb0, 0x39, 0x79, 0xd4, 0x64, 0xc1, 0x0a, 0xfc, 0x19, 0xec, 0xa7,
	0x68, 0xab, 0x1f, 0x05, 0xee, 0x58, 0xab, 0x0b, 0xc7, 0x73, 0x34, 0x2b, 0xe7, 0xed, 0xb7, 0xc6,
	0x03, 0x9c, 0x40, 0xb6, 0xcc, 0x0f, 0x61, 0x6f, 0x0e, 0x36, 0x5b, 0x56, 0xf2, 0x5c, 0x67, 0xa4,
	0x06, 0x8e, 0x70, 0x0d, 0xb7, 0xda, 0xfc, 0xb3, 0x08, 0x6b, 0xd7, 0x99, 0xd7, 0x6e, 0xea, 0xdb,
	0x88, 0xbd, 0xb7, 0x7e, 0x34, 0xee, 0x7b, 0x8e, 0xd6, 0x4a, 0xb2, 0x25, 0x5e, 0x87, 0xed, 0x3c,
	0x69, 0xb2, 0xfb, 0x67, 0xfa, 0x59, 0xfc, 0x05, 0x1c, 0x64, 0x35, 0xde, 0x09, 0x47, 0x3b, 0xfe,
	0xb0, 0x43, 0x36, 0x98, 0x95, 0x44, 0x12, 0xd3, 0x06, 0x47, 0x0d, 0x56, 0xe0, 0xcf, 0xa1, 0x36,
	0xcf, 0x9d, 0x09, 0xc7, 0x55, 0x92, 0x15, 0xf9, 0x7e, 0xde, 0x35, 0x1e, 0x85, 0xeb, 0xb1, 0x66,
	0x25, 0x7e, 0x00, 0xbb, 0x0b, 0x4c, 0x2a, 0xc9, 0xca, 0xb3, 0xb9, 0xe0, 0x3b, 0xa1, 0x64, 0xef,
	0x46, 0x84, 0x9a, 0xc1, 0x6c, 0x28, 0x31, 0xd9, 0x72, 0x5d, 0xb6, 0xc6, 0x5f, 0xc1, 0xb3, 0x2c,
	0xd7, 0x16, 0xfe, 0x40, 0xb9, 0xae, 0xe3, 0x0f, 0xcd, 0xe6, 0x2a, 0x7f, 0x09, 0x87, 0x1f, 0x50,
	0x40, 0x03, 0xeb, 0x1f, 0xe0, 0xa7, 0xce, 0x37, 0x66, 0xcb, 0x94, 0xf2, 0xb8, 0x7d, 0x13, 0x07,
	0x3b, 0x17, 0x9b, 0x29, 0xc2, 0x2e, 0x1e, 0xa6, 0x2c, 0x7e, 0xe2, 0x44, 0xa2, 0x8f, 0xcc, 0xde,
	0x6c, 0x79, 0x4e, 0x94, 0xab, 0xb0, 0x06, 0xfb, 0xcd, 0xef, 0xa0, 0x7a, 0x93, 0xfd, 0x9f, 0xdd,
	0x85, 0xad, 0xac, 0xdc, 0xbb, 0x08, 0xfc, 0x21, 0x5b, 0xe2, 0x9f, 0xc1, 0x4e, 0x0e, 0x5e, 0xd0,
	0xda, 0x3d, 0xe0, 0x39, 0x15, 0x73, 0x26, 0xac, 0xe6, 0xaf, 0x16, 0xac, 0x5f, 0x06, 0xd2, 0xb9,
	0x9b, 0x50, 0x04, 0xd7, 0x23, 0x6c, 0x49, 0x0e, 0xc8, 0x1c, 0x83, 0x1a, 0xec, 0xe4, 0xa9, 0xe4,
	0x28, 0xcc, 0x31, 0xa6, 0x28, 0xac, 0x30, 0x6f, 0x2e, 0xce, 0x9b, 0x15, 0xe7, 0x37, 0x9d, 0xfa,
	0xc4, 0x94, 0xe6, 0x19, 0x53, 0x12, 0x56, 0x6e, 0xfe, 0x6c, 0xc1, 0x8e, 0xad, 0x06, 0x81, 0x7f,
	0xe7, 0x84, 0x1e, 0xb1, 0xb6, 0x12, 0x51, 0xe0, 0xf3, 0x3a, 0x3c, 0x5f, 0x84, 0x67, 0xa2, 0xff,
	0x1c, 0xea, 0x0b, 0x35, 0x6e, 0xf5, 0xa4, 0x1b, 0x04, 0x17, 0x22, 0x1c, 0x2a, 0x66, 0xf1, 0x2f,
	0xa0, 0xb1, 0x50, 0x8b, 0x7e, 0xa4, 0x5a, 0x7d, 0xdf, 0x64, 0x5c, 0xf8, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x67, 0xf5, 0xda, 0xfc, 0x75, 0x0e, 0x00, 0x00,
}
