// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetGlobalState.proto

package GetGlobalState

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProgramStatusType int32

const (
	ProgramStatusType_ProgramStatusType_None                 ProgramStatusType = 0
	ProgramStatusType_ProgramStatusType_Loaded               ProgramStatusType = 1
	ProgramStatusType_ProgramStatusType_Loging               ProgramStatusType = 2
	ProgramStatusType_ProgramStatusType_NeedPicVerifyCode    ProgramStatusType = 3
	ProgramStatusType_ProgramStatusType_NeedPhoneVerifyCode  ProgramStatusType = 4
	ProgramStatusType_ProgramStatusType_LoginFailed          ProgramStatusType = 5
	ProgramStatusType_ProgramStatusType_ForceUpdate          ProgramStatusType = 6
	ProgramStatusType_ProgramStatusType_NessaryDataPreparing ProgramStatusType = 7
	ProgramStatusType_ProgramStatusType_NessaryDataMissing   ProgramStatusType = 8
	ProgramStatusType_ProgramStatusType_UnAgreeDisclaimer    ProgramStatusType = 9
	ProgramStatusType_ProgramStatusType_Ready                ProgramStatusType = 10
	//OpenD登录后被强制退出登录，会导致连接全部断开,需要重连后才能得到以下该状态（并且需要在ui模式下）
	ProgramStatusType_ProgramStatusType_ForceLogout ProgramStatusType = 11
)

var ProgramStatusType_name = map[int32]string{
	0:  "ProgramStatusType_None",
	1:  "ProgramStatusType_Loaded",
	2:  "ProgramStatusType_Loging",
	3:  "ProgramStatusType_NeedPicVerifyCode",
	4:  "ProgramStatusType_NeedPhoneVerifyCode",
	5:  "ProgramStatusType_LoginFailed",
	6:  "ProgramStatusType_ForceUpdate",
	7:  "ProgramStatusType_NessaryDataPreparing",
	8:  "ProgramStatusType_NessaryDataMissing",
	9:  "ProgramStatusType_UnAgreeDisclaimer",
	10: "ProgramStatusType_Ready",
	11: "ProgramStatusType_ForceLogout",
}

var ProgramStatusType_value = map[string]int32{
	"ProgramStatusType_None":                 0,
	"ProgramStatusType_Loaded":               1,
	"ProgramStatusType_Loging":               2,
	"ProgramStatusType_NeedPicVerifyCode":    3,
	"ProgramStatusType_NeedPhoneVerifyCode":  4,
	"ProgramStatusType_LoginFailed":          5,
	"ProgramStatusType_ForceUpdate":          6,
	"ProgramStatusType_NessaryDataPreparing": 7,
	"ProgramStatusType_NessaryDataMissing":   8,
	"ProgramStatusType_UnAgreeDisclaimer":    9,
	"ProgramStatusType_Ready":                10,
	"ProgramStatusType_ForceLogout":          11,
}

func (x ProgramStatusType) Enum() *ProgramStatusType {
	p := new(ProgramStatusType)
	*p = x
	return p
}

func (x ProgramStatusType) String() string {
	return proto.EnumName(ProgramStatusType_name, int32(x))
}

func (x *ProgramStatusType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProgramStatusType_value, data, "ProgramStatusType")
	if err != nil {
		return err
	}
	*x = ProgramStatusType(value)
	return nil
}

func (ProgramStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59f43160a8f8c3c7, []int{0}
}

type ProgramStatus struct {
	Type                 *ProgramStatusType `protobuf:"varint,1,req,name=type,enum=GetGlobalState.ProgramStatusType" json:"type,omitempty"`
	StrExtDesc           *string            `protobuf:"bytes,2,opt,name=strExtDesc" json:"strExtDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProgramStatus) Reset()         { *m = ProgramStatus{} }
func (m *ProgramStatus) String() string { return proto.CompactTextString(m) }
func (*ProgramStatus) ProtoMessage()    {}
func (*ProgramStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f43160a8f8c3c7, []int{0}
}

func (m *ProgramStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgramStatus.Unmarshal(m, b)
}
func (m *ProgramStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgramStatus.Marshal(b, m, deterministic)
}
func (m *ProgramStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgramStatus.Merge(m, src)
}
func (m *ProgramStatus) XXX_Size() int {
	return xxx_messageInfo_ProgramStatus.Size(m)
}
func (m *ProgramStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgramStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProgramStatus proto.InternalMessageInfo

func (m *ProgramStatus) GetType() ProgramStatusType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProgramStatusType_ProgramStatusType_None
}

func (m *ProgramStatus) GetStrExtDesc() string {
	if m != nil && m.StrExtDesc != nil {
		return *m.StrExtDesc
	}
	return ""
}

type C2S struct {
	UserID               *uint64  `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f43160a8f8c3c7, []int{1}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type S2C struct {
	MarketHK             *int32         `protobuf:"varint,1,req,name=marketHK" json:"marketHK,omitempty"`
	MarketUS             *int32         `protobuf:"varint,2,req,name=marketUS" json:"marketUS,omitempty"`
	MarketSH             *int32         `protobuf:"varint,3,req,name=marketSH" json:"marketSH,omitempty"`
	MarketSZ             *int32         `protobuf:"varint,4,req,name=marketSZ" json:"marketSZ,omitempty"`
	MarketHKFuture       *int32         `protobuf:"varint,5,req,name=marketHKFuture" json:"marketHKFuture,omitempty"`
	QotLogined           *bool          `protobuf:"varint,6,req,name=qotLogined" json:"qotLogined,omitempty"`
	TrdLogined           *bool          `protobuf:"varint,7,req,name=trdLogined" json:"trdLogined,omitempty"`
	ServerVer            *int32         `protobuf:"varint,8,req,name=serverVer" json:"serverVer,omitempty"`
	ServerBuildNo        *int32         `protobuf:"varint,9,req,name=serverBuildNo" json:"serverBuildNo,omitempty"`
	Time                 *int64         `protobuf:"varint,10,req,name=time" json:"time,omitempty"`
	LocalTime            *float64       `protobuf:"fixed64,11,opt,name=localTime" json:"localTime,omitempty"`
	ProgramStatus        *ProgramStatus `protobuf:"bytes,12,opt,name=programStatus" json:"programStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f43160a8f8c3c7, []int{2}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetMarketHK() int32 {
	if m != nil && m.MarketHK != nil {
		return *m.MarketHK
	}
	return 0
}

func (m *S2C) GetMarketUS() int32 {
	if m != nil && m.MarketUS != nil {
		return *m.MarketUS
	}
	return 0
}

func (m *S2C) GetMarketSH() int32 {
	if m != nil && m.MarketSH != nil {
		return *m.MarketSH
	}
	return 0
}

func (m *S2C) GetMarketSZ() int32 {
	if m != nil && m.MarketSZ != nil {
		return *m.MarketSZ
	}
	return 0
}

func (m *S2C) GetMarketHKFuture() int32 {
	if m != nil && m.MarketHKFuture != nil {
		return *m.MarketHKFuture
	}
	return 0
}

func (m *S2C) GetQotLogined() bool {
	if m != nil && m.QotLogined != nil {
		return *m.QotLogined
	}
	return false
}

func (m *S2C) GetTrdLogined() bool {
	if m != nil && m.TrdLogined != nil {
		return *m.TrdLogined
	}
	return false
}

func (m *S2C) GetServerVer() int32 {
	if m != nil && m.ServerVer != nil {
		return *m.ServerVer
	}
	return 0
}

func (m *S2C) GetServerBuildNo() int32 {
	if m != nil && m.ServerBuildNo != nil {
		return *m.ServerBuildNo
	}
	return 0
}

func (m *S2C) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *S2C) GetLocalTime() float64 {
	if m != nil && m.LocalTime != nil {
		return *m.LocalTime
	}
	return 0
}

func (m *S2C) GetProgramStatus() *ProgramStatus {
	if m != nil {
		return m.ProgramStatus
	}
	return nil
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f43160a8f8c3c7, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f43160a8f8c3c7, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterEnum("GetGlobalState.ProgramStatusType", ProgramStatusType_name, ProgramStatusType_value)
	proto.RegisterType((*ProgramStatus)(nil), "GetGlobalState.ProgramStatus")
	proto.RegisterType((*C2S)(nil), "GetGlobalState.C2S")
	proto.RegisterType((*S2C)(nil), "GetGlobalState.S2C")
	proto.RegisterType((*Request)(nil), "GetGlobalState.Request")
	proto.RegisterType((*Response)(nil), "GetGlobalState.Response")
}

func init() { proto.RegisterFile("GetGlobalState.proto", fileDescriptor_59f43160a8f8c3c7) }

var fileDescriptor_59f43160a8f8c3c7 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0xaf, 0x63, 0x87, 0x24, 0x27, 0x80, 0x7c, 0xe7, 0x5e, 0xd1, 0x51, 0x0a, 0x95, 0x49,
	0x81, 0xba, 0x48, 0x45, 0xc8, 0x6a, 0x37, 0xdd, 0xb5, 0x4e, 0x81, 0xaa, 0x80, 0xe8, 0x98, 0xb0,
	0x60, 0x83, 0xa6, 0xf6, 0xc1, 0xb5, 0xea, 0x78, 0xcc, 0xcc, 0xb8, 0x6a, 0xd6, 0x7d, 0x89, 0x3e,
	0x50, 0x1f, 0xac, 0xb2, 0x21, 0x8d, 0x43, 0x02, 0x3b, 0x9f, 0xef, 0xf7, 0xf9, 0xfc, 0x99, 0x73,
	0xe0, 0xff, 0x43, 0xd4, 0x87, 0xa9, 0xf8, 0xc2, 0xd3, 0x40, 0x73, 0x8d, 0x7b, 0xb9, 0x14, 0x5a,
	0x90, 0xd5, 0x59, 0xb5, 0xb7, 0xec, 0x8b, 0xd1, 0x48, 0x64, 0xb7, 0xb4, 0x67, 0x7f, 0x16, 0xfa,
	0xaa, 0xae, 0xf4, 0xaf, 0x61, 0xe5, 0x4c, 0x8a, 0x58, 0xf2, 0x51, 0xe9, 0x2f, 0x14, 0x79, 0x03,
	0x96, 0x1e, 0xe7, 0x48, 0x0d, 0xa7, 0xe1, 0xae, 0x7a, 0x9b, 0x7b, 0xf7, 0xaa, 0xcc, 0x98, 0xcf,
	0xc7, 0x39, 0xb2, 0xca, 0x4e, 0x9e, 0x01, 0x28, 0x2d, 0x3f, 0xfc, 0xd0, 0x03, 0x54, 0x21, 0x6d,
	0x38, 0x86, 0xdb, 0x61, 0x35, 0xa5, 0xbf, 0x01, 0xa6, 0xef, 0x05, 0x64, 0x0d, 0x96, 0x0a, 0x85,
	0xf2, 0xe3, 0xa0, 0xca, 0x6f, 0xb1, 0xbb, 0xa8, 0xff, 0xcb, 0x04, 0x33, 0xf0, 0x7c, 0xd2, 0x83,
	0xf6, 0x88, 0xcb, 0x6f, 0xa8, 0x8f, 0x3e, 0x55, 0x8e, 0x26, 0xfb, 0x1b, 0x4f, 0xd9, 0x30, 0xa0,
	0x8d, 0x3a, 0x1b, 0x06, 0x53, 0x16, 0x1c, 0x51, 0xb3, 0xce, 0x82, 0xa3, 0x1a, 0xbb, 0xa4, 0xd6,
	0x0c, 0xbb, 0x24, 0x3b, 0xb0, 0x3a, 0xc9, 0x7f, 0x50, 0xe8, 0x42, 0x22, 0x6d, 0x56, 0x8e, 0x7b,
	0x6a, 0x39, 0xde, 0x8d, 0xd0, 0xc7, 0x22, 0x4e, 0x32, 0x8c, 0xe8, 0x92, 0xd3, 0x70, 0xdb, 0xac,
	0xa6, 0x94, 0x5c, 0xcb, 0x68, 0xc2, 0x5b, 0xb7, 0x7c, 0xaa, 0x90, 0x75, 0xe8, 0x28, 0x94, 0xdf,
	0x51, 0x5e, 0xa0, 0xa4, 0xed, 0xaa, 0xc4, 0x54, 0x20, 0x5b, 0xb0, 0x72, 0x1b, 0xbc, 0x2f, 0x92,
	0x34, 0x3a, 0x15, 0xb4, 0x53, 0x39, 0x66, 0x45, 0x42, 0xc0, 0xd2, 0xc9, 0x08, 0x29, 0x38, 0x0d,
	0xd7, 0x64, 0xd5, 0x77, 0x99, 0x37, 0x15, 0x21, 0x4f, 0xcf, 0x4b, 0xd0, 0x75, 0x0c, 0xd7, 0x60,
	0x53, 0x81, 0xf8, 0xb0, 0x92, 0xd7, 0xf7, 0x45, 0x97, 0x1d, 0xc3, 0xed, 0x7a, 0x1b, 0x8f, 0x2e,
	0x95, 0xcd, 0xfe, 0xd3, 0xdf, 0x87, 0x16, 0xc3, 0x9b, 0x02, 0x95, 0x26, 0xdb, 0x60, 0x86, 0x9e,
	0xaa, 0x16, 0xd3, 0xf5, 0xfe, 0xbb, 0x9f, 0xc5, 0xf7, 0x02, 0x56, 0xf2, 0xfe, 0x4f, 0x03, 0xda,
	0x0c, 0x55, 0x2e, 0x32, 0x55, 0xbe, 0x5c, 0x4b, 0xa2, 0x3e, 0x9f, 0x9c, 0x54, 0xf3, 0xad, 0xf5,
	0xea, 0xf5, 0xfe, 0x3e, 0x9b, 0x88, 0xe5, 0x45, 0x48, 0xd4, 0x27, 0x2a, 0xbe, 0x3b, 0x9a, 0xbb,
	0x88, 0x50, 0x68, 0xa1, 0x94, 0xbe, 0x88, 0x90, 0x9a, 0x8e, 0xe1, 0x36, 0xd9, 0x24, 0x2c, 0xbb,
	0x50, 0x5e, 0x48, 0xad, 0x6a, 0x96, 0xb9, 0x2e, 0x02, 0xcf, 0x67, 0x25, 0xdf, 0xfd, 0x6d, 0xc2,
	0xbf, 0x73, 0xd7, 0x4a, 0x7a, 0xb0, 0x36, 0x27, 0x5e, 0x9d, 0x8a, 0x0c, 0xed, 0x7f, 0xc8, 0x3a,
	0xd0, 0x79, 0x76, 0x2c, 0x78, 0x84, 0x91, 0x6d, 0x3c, 0x44, 0xe3, 0x24, 0x8b, 0xed, 0x06, 0x79,
	0x01, 0xcf, 0x17, 0xe4, 0x45, 0x8c, 0xce, 0x92, 0xf0, 0x02, 0x65, 0x72, 0x3d, 0x2e, 0x7b, 0xb7,
	0x4d, 0xf2, 0x12, 0xb6, 0x1f, 0x30, 0x7e, 0x15, 0x19, 0xd6, 0xac, 0x16, 0xd9, 0x84, 0x8d, 0x07,
	0x2a, 0x1e, 0xf0, 0x24, 0xc5, 0xc8, 0x6e, 0x2e, 0xb6, 0x1c, 0x08, 0x19, 0xe2, 0x30, 0x8f, 0xb8,
	0x46, 0x7b, 0x89, 0xec, 0xc2, 0xce, 0xa2, 0x82, 0x4a, 0x71, 0x39, 0x1e, 0x70, 0xcd, 0xcf, 0x24,
	0xe6, 0x5c, 0x96, 0x53, 0xb4, 0x88, 0x0b, 0x5b, 0x8f, 0x7a, 0x4f, 0x12, 0xa5, 0x4a, 0x67, 0x7b,
	0xf1, 0xbc, 0xc3, 0xec, 0x5d, 0x2c, 0x11, 0x07, 0x89, 0x0a, 0x53, 0x9e, 0x8c, 0x50, 0xda, 0x1d,
	0xf2, 0x14, 0x9e, 0xcc, 0x1b, 0x19, 0xf2, 0x68, 0x6c, 0xc3, 0x23, 0xed, 0x1f, 0x8b, 0x58, 0x14,
	0xda, 0xee, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x42, 0x0f, 0x1d, 0x28, 0xe7, 0x04, 0x00, 0x00,
}
