// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_GetRT.proto

package Qot_GetRT

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2S struct {
	Security             *Security `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_589d2a49067bde4d, []int{0}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

type S2C struct {
	Security             *Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	RtList               []*TimeShare `protobuf:"bytes,2,rep,name=rtList" json:"rtList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_589d2a49067bde4d, []int{1}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *S2C) GetRtList() []*TimeShare {
	if m != nil {
		return m.RtList
	}
	return nil
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_589d2a49067bde4d, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_589d2a49067bde4d, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S)(nil), "Qot_GetRT.C2S")
	proto.RegisterType((*S2C)(nil), "Qot_GetRT.S2C")
	proto.RegisterType((*Request)(nil), "Qot_GetRT.Request")
	proto.RegisterType((*Response)(nil), "Qot_GetRT.Response")
}

func init() { proto.RegisterFile("Qot_GetRT.proto", fileDescriptor_589d2a49067bde4d) }

var fileDescriptor_589d2a49067bde4d = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8f, 0xb1, 0x4b, 0xc3, 0x40,
	0x14, 0xc6, 0x49, 0xd2, 0x36, 0xed, 0xab, 0xa8, 0x1c, 0x2a, 0x47, 0x07, 0x39, 0x32, 0x05, 0xa4,
	0x21, 0x1c, 0x82, 0xe0, 0x7a, 0x83, 0x8b, 0x0e, 0xbe, 0xcb, 0x2e, 0x12, 0x9f, 0x9a, 0x21, 0xbd,
	0x78, 0xf7, 0x3a, 0x74, 0xf1, 0x6f, 0x97, 0x68, 0x5a, 0x83, 0x9b, 0xe3, 0xfb, 0x7e, 0xbf, 0x8f,
	0x8f, 0x07, 0x27, 0x8f, 0x8e, 0x9f, 0xee, 0x88, 0xb1, 0x2a, 0x3a, 0xef, 0xd8, 0x89, 0xc5, 0x21,
	0x58, 0x1d, 0x19, 0xd7, 0xb6, 0x6e, 0xf3, 0x03, 0x56, 0xa7, 0x3d, 0x18, 0x27, 0xd9, 0x0d, 0x24,
	0x46, 0x5b, 0x51, 0xc2, 0x3c, 0x50, 0xbd, 0xf5, 0x0d, 0xef, 0x64, 0xa4, 0xe2, 0x7c, 0xa9, 0xcf,
	0x8a, 0x91, 0x6b, 0x07, 0x86, 0x07, 0x2b, 0x7b, 0x85, 0xc4, 0x6a, 0xf3, 0xff, 0xa2, 0x58, 0xc3,
	0xcc, 0xf3, 0x7d, 0x13, 0x58, 0xc6, 0x2a, 0xc9, 0x97, 0xfa, 0x7c, 0xec, 0x57, 0x4d, 0x4b, 0xf6,
	0xfd, 0xd9, 0x13, 0x0e, 0x52, 0x76, 0x05, 0x29, 0xd2, 0xc7, 0x96, 0x02, 0x0b, 0x05, 0x49, 0xad,
	0xc3, 0x30, 0x73, 0x5c, 0xfc, 0x7e, 0x6d, 0xb4, 0xc5, 0x1e, 0x65, 0x9f, 0x30, 0x47, 0x0a, 0x9d,
	0xdb, 0x04, 0x12, 0x97, 0x90, 0x7a, 0xe2, 0x6a, 0xd7, 0xd1, 0x77, 0x63, 0x7a, 0x3b, 0x59, 0x5f,
	0x97, 0x25, 0xee, 0x43, 0x71, 0x01, 0x33, 0x4f, 0xfc, 0x10, 0xde, 0x64, 0xac, 0xa2, 0x7c, 0x81,
	0xc3, 0x25, 0x24, 0xa4, 0xe4, 0xbd, 0x71, 0x2f, 0x24, 0x13, 0x15, 0xe5, 0x53, 0xdc, 0x9f, 0xfd,
	0x7e, 0xd0, 0xb5, 0x9c, 0xa8, 0xe8, 0xcf, 0xbe, 0xd5, 0x06, 0x7b, 0xf4, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x40, 0x15, 0xb5, 0x8a, 0x01, 0x00, 0x00,
}
