// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetUserInfo.proto

package GetUserInfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//行情权限
type QotRight int32

const (
	QotRight_QotRight_Unknow QotRight = 0
	QotRight_QotRight_Bmp    QotRight = 1
	QotRight_QotRight_Level1 QotRight = 2
	QotRight_QotRight_Level2 QotRight = 3
)

var QotRight_name = map[int32]string{
	0: "QotRight_Unknow",
	1: "QotRight_Bmp",
	2: "QotRight_Level1",
	3: "QotRight_Level2",
}

var QotRight_value = map[string]int32{
	"QotRight_Unknow": 0,
	"QotRight_Bmp":    1,
	"QotRight_Level1": 2,
	"QotRight_Level2": 3,
}

func (x QotRight) Enum() *QotRight {
	p := new(QotRight)
	*p = x
	return p
}

func (x QotRight) String() string {
	return proto.EnumName(QotRight_name, int32(x))
}

func (x *QotRight) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QotRight_value, data, "QotRight")
	if err != nil {
		return err
	}
	*x = QotRight(value)
	return nil
}

func (QotRight) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb345f7e707afc7e, []int{0}
}

type C2S struct {
	UserID               *uint64  `protobuf:"varint,1,req,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb345f7e707afc7e, []int{0}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type S2C struct {
	NickName              *string  `protobuf:"bytes,1,req,name=nickName" json:"nickName,omitempty"`
	AvatarUrl             *string  `protobuf:"bytes,2,req,name=avatarUrl" json:"avatarUrl,omitempty"`
	ApiLevel              *string  `protobuf:"bytes,3,req,name=apiLevel" json:"apiLevel,omitempty"`
	HkQotRight            *int32   `protobuf:"varint,4,req,name=hkQotRight" json:"hkQotRight,omitempty"`
	UsQotRight            *int32   `protobuf:"varint,5,req,name=usQotRight" json:"usQotRight,omitempty"`
	CnQotRight            *int32   `protobuf:"varint,6,req,name=cnQotRight" json:"cnQotRight,omitempty"`
	IsNeedAgreeDisclaimer *bool    `protobuf:"varint,7,req,name=isNeedAgreeDisclaimer" json:"isNeedAgreeDisclaimer,omitempty"`
	UserID                *int64   `protobuf:"varint,8,req,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb345f7e707afc7e, []int{1}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *S2C) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *S2C) GetApiLevel() string {
	if m != nil && m.ApiLevel != nil {
		return *m.ApiLevel
	}
	return ""
}

func (m *S2C) GetHkQotRight() int32 {
	if m != nil && m.HkQotRight != nil {
		return *m.HkQotRight
	}
	return 0
}

func (m *S2C) GetUsQotRight() int32 {
	if m != nil && m.UsQotRight != nil {
		return *m.UsQotRight
	}
	return 0
}

func (m *S2C) GetCnQotRight() int32 {
	if m != nil && m.CnQotRight != nil {
		return *m.CnQotRight
	}
	return 0
}

func (m *S2C) GetIsNeedAgreeDisclaimer() bool {
	if m != nil && m.IsNeedAgreeDisclaimer != nil {
		return *m.IsNeedAgreeDisclaimer
	}
	return false
}

func (m *S2C) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb345f7e707afc7e, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb345f7e707afc7e, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterEnum("GetUserInfo.QotRight", QotRight_name, QotRight_value)
	proto.RegisterType((*C2S)(nil), "GetUserInfo.C2S")
	proto.RegisterType((*S2C)(nil), "GetUserInfo.S2C")
	proto.RegisterType((*Request)(nil), "GetUserInfo.Request")
	proto.RegisterType((*Response)(nil), "GetUserInfo.Response")
}

func init() { proto.RegisterFile("GetUserInfo.proto", fileDescriptor_cb345f7e707afc7e) }

var fileDescriptor_cb345f7e707afc7e = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0xcd, 0x24, 0xd9, 0xa4, 0x6f, 0x17, 0x8c, 0x23, 0xca, 0xb0, 0xe8, 0x12, 0x72, 0x0a,
	0xc2, 0x2e, 0xeb, 0xb0, 0x27, 0x6f, 0x9a, 0x82, 0x08, 0x5a, 0x70, 0x62, 0x4f, 0x1e, 0x24, 0xa4,
	0xcf, 0x36, 0xb4, 0xc9, 0xc4, 0x99, 0x69, 0xc5, 0x9b, 0x57, 0xff, 0x6b, 0x99, 0xa4, 0x49, 0x23,
	0xf5, 0x96, 0xef, 0xf7, 0x7b, 0x8f, 0x3c, 0xbe, 0x81, 0x27, 0xef, 0xd1, 0x2c, 0x35, 0xaa, 0x0f,
	0xcd, 0x77, 0x79, 0xd7, 0x2a, 0x69, 0x24, 0xbd, 0x9c, 0xa0, 0xeb, 0xab, 0x4c, 0xd6, 0xb5, 0x6c,
	0x7a, 0x95, 0xbc, 0x04, 0x37, 0xe3, 0x39, 0x7d, 0x0e, 0x17, 0x7b, 0x3b, 0x30, 0x67, 0x4e, 0x4c,
	0x52, 0x4f, 0x1c, 0x53, 0xf2, 0x87, 0x80, 0x9b, 0xf3, 0x8c, 0x5e, 0x43, 0xd8, 0x54, 0xe5, 0x76,
	0x51, 0xd4, 0xd8, 0x4d, 0xcc, 0xc4, 0x98, 0xe9, 0x0b, 0x98, 0x15, 0x87, 0xc2, 0x14, 0x6a, 0xa9,
	0x76, 0x8c, 0x74, 0xf2, 0x04, 0xec, 0x66, 0xd1, 0x56, 0x1f, 0xf1, 0x80, 0x3b, 0xe6, 0xf6, 0x9b,
	0x43, 0xa6, 0x37, 0x00, 0x9b, 0xed, 0x67, 0x69, 0x44, 0xb5, 0xde, 0x18, 0xe6, 0xc5, 0x24, 0xf5,
	0xc5, 0x84, 0x58, 0xbf, 0xd7, 0xa3, 0xf7, 0x7b, 0x7f, 0x22, 0xd6, 0x97, 0xcd, 0xe8, 0x2f, 0x7a,
	0x7f, 0x22, 0xf4, 0x01, 0x9e, 0x55, 0x7a, 0x81, 0xb8, 0x7a, 0xbb, 0x56, 0x88, 0xf3, 0x4a, 0x97,
	0xbb, 0xa2, 0xaa, 0x51, 0xb1, 0x20, 0x26, 0x69, 0x28, 0xfe, 0x2f, 0x27, 0x5d, 0x84, 0x31, 0x49,
	0xdd, 0xb1, 0x8b, 0x5b, 0x08, 0x04, 0xfe, 0xd8, 0xa3, 0x36, 0x34, 0x01, 0xb7, 0xe4, 0xba, 0x6b,
	0xe2, 0x92, 0x47, 0x77, 0xd3, 0xc6, 0x33, 0x9e, 0x0b, 0x2b, 0x93, 0xdf, 0x0e, 0x84, 0x02, 0x75,
	0x2b, 0x1b, 0x8d, 0xf4, 0x06, 0x02, 0x85, 0xe6, 0xcb, 0xaf, 0xb6, 0xaf, 0xcf, 0x7f, 0xe3, 0xdd,
	0x3e, 0xdc, 0xdf, 0x8b, 0x01, 0xda, 0x7f, 0x2a, 0x34, 0x9f, 0xf4, 0x9a, 0x91, 0xd8, 0x49, 0x67,
	0xe2, 0x98, 0x28, 0x83, 0x00, 0x95, 0xca, 0xe4, 0x0a, 0x99, 0x1b, 0x3b, 0xa9, 0x2f, 0x86, 0x68,
	0x4f, 0xd0, 0xbc, 0x64, 0x5e, 0xec, 0x9c, 0x9d, 0x90, 0xf3, 0x4c, 0x58, 0xf9, 0xea, 0x2b, 0x84,
	0x63, 0x17, 0x4f, 0xe1, 0xf1, 0xf0, 0xfd, 0x6d, 0xd9, 0x6c, 0x1b, 0xf9, 0x33, 0x7a, 0x44, 0x23,
	0xb8, 0x1a, 0xe1, 0xbb, 0xba, 0x8d, 0x9c, 0x7f, 0xc6, 0xba, 0x47, 0x7a, 0x1d, 0x91, 0x73, 0xc8,
	0x23, 0xf7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xca, 0x97, 0x5b, 0x68, 0x02, 0x00, 0x00,
}
