// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_UpdateRT.proto

package Qot_UpdateRT

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S2C struct {
	Security             *Security    `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	RtList               []*TimeShare `protobuf:"bytes,2,rep,name=rtList" json:"rtList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab39aef1b2db6851, []int{0}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *S2C) GetRtList() []*TimeShare {
	if m != nil {
		return m.RtList
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab39aef1b2db6851, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterType((*S2C)(nil), "Qot_UpdateRT.S2C")
	proto.RegisterType((*Response)(nil), "Qot_UpdateRT.Response")
}

func init() { proto.RegisterFile("Qot_UpdateRT.proto", fileDescriptor_ab39aef1b2db6851) }

var fileDescriptor_ab39aef1b2db6851 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0x47, 0xe5, 0xa4, 0xff, 0xb8, 0x74, 0x00, 0x0b, 0x90, 0xd5, 0x01, 0x59, 0x65, 0xf1, 0xd2,
	0x28, 0xb2, 0x98, 0x58, 0xb3, 0xc2, 0xc0, 0x25, 0xcc, 0xa8, 0x6a, 0x0f, 0xc8, 0x90, 0x3a, 0x3a,
	0x1f, 0x43, 0x47, 0xbe, 0x39, 0x2a, 0x24, 0x28, 0x1d, 0x7f, 0xef, 0x3d, 0xe9, 0xa4, 0x03, 0xfd,
	0x12, 0xe4, 0xed, 0xb5, 0xdb, 0x6f, 0x85, 0xb0, 0xce, 0x3b, 0x0e, 0x12, 0xf4, 0x72, 0xcc, 0x56,
	0xcb, 0x32, 0xb4, 0x6d, 0x38, 0xfc, 0xb9, 0xd5, 0xe5, 0xc9, 0x8d, 0xc9, 0xfa, 0x1d, 0xd2, 0xca,
	0x97, 0xba, 0x80, 0x45, 0xa4, 0xdd, 0x17, 0x37, 0x72, 0x34, 0xca, 0x26, 0x2e, 0xf3, 0xd7, 0xf9,
	0xa8, 0xad, 0x7a, 0x87, 0xff, 0x95, 0xde, 0xc0, 0x8c, 0xe5, 0xa9, 0x89, 0x62, 0x12, 0x9b, 0xba,
	0xcc, 0xdf, 0x8c, 0xfb, 0xba, 0x69, 0xa9, 0xfa, 0xdc, 0x32, 0x61, 0x1f, 0xad, 0xbf, 0x15, 0x2c,
	0x90, 0x62, 0x17, 0x0e, 0x91, 0xf4, 0x1d, 0xcc, 0x99, 0xa4, 0x3e, 0x76, 0xf4, 0x7b, 0x6c, 0xfa,
	0x38, 0xd9, 0x3c, 0x14, 0x05, 0x0e, 0x50, 0xdf, 0xc2, 0x8c, 0x49, 0x9e, 0xe3, 0x87, 0x49, 0xac,
	0x72, 0x17, 0xd8, 0x2f, 0x6d, 0x60, 0x4e, 0xcc, 0x65, 0xd8, 0x93, 0x49, 0xad, 0x72, 0x53, 0x1c,
	0xa6, 0xbe, 0x87, 0x34, 0xfa, 0x9d, 0x99, 0x58, 0xe5, 0x32, 0x7f, 0x95, 0x9f, 0xbd, 0xa5, 0xf2,
	0x25, 0x9e, 0xec, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x23, 0xaf, 0xed, 0x2e, 0x01, 0x00,
	0x00,
}
