// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Qot_GetOptionChain.proto

package Qot_GetOptionChain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OptionCondType int32

const (
	OptionCondType_OptionCondType_Unknow  OptionCondType = 0
	OptionCondType_OptionCondType_WithIn  OptionCondType = 1
	OptionCondType_OptionCondType_Outside OptionCondType = 2
)

var OptionCondType_name = map[int32]string{
	0: "OptionCondType_Unknow",
	1: "OptionCondType_WithIn",
	2: "OptionCondType_Outside",
}

var OptionCondType_value = map[string]int32{
	"OptionCondType_Unknow":  0,
	"OptionCondType_WithIn":  1,
	"OptionCondType_Outside": 2,
}

func (x OptionCondType) Enum() *OptionCondType {
	p := new(OptionCondType)
	*p = x
	return p
}

func (x OptionCondType) String() string {
	return proto.EnumName(OptionCondType_name, int32(x))
}

func (x *OptionCondType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OptionCondType_value, data, "OptionCondType")
	if err != nil {
		return err
	}
	*x = OptionCondType(value)
	return nil
}

func (OptionCondType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{0}
}

type C2S struct {
	Owner                *Security `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Type                 *int32    `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Condition            *int32    `protobuf:"varint,3,opt,name=condition" json:"condition,omitempty"`
	BeginTime            *string   `protobuf:"bytes,4,req,name=beginTime" json:"beginTime,omitempty"`
	EndTime              *string   `protobuf:"bytes,5,req,name=endTime" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{0}
}

func (m *C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S.Unmarshal(m, b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return xxx_messageInfo_C2S.Size(m)
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetOwner() *Security {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *C2S) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *C2S) GetCondition() int32 {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return 0
}

func (m *C2S) GetBeginTime() string {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return ""
}

func (m *C2S) GetEndTime() string {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return ""
}

type OptionItem struct {
	Call                 *SecurityStaticInfo `protobuf:"bytes,1,opt,name=call" json:"call,omitempty"`
	Put                  *SecurityStaticInfo `protobuf:"bytes,2,opt,name=put" json:"put,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OptionItem) Reset()         { *m = OptionItem{} }
func (m *OptionItem) String() string { return proto.CompactTextString(m) }
func (*OptionItem) ProtoMessage()    {}
func (*OptionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{1}
}

func (m *OptionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionItem.Unmarshal(m, b)
}
func (m *OptionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionItem.Marshal(b, m, deterministic)
}
func (m *OptionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionItem.Merge(m, src)
}
func (m *OptionItem) XXX_Size() int {
	return xxx_messageInfo_OptionItem.Size(m)
}
func (m *OptionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionItem.DiscardUnknown(m)
}

var xxx_messageInfo_OptionItem proto.InternalMessageInfo

func (m *OptionItem) GetCall() *SecurityStaticInfo {
	if m != nil {
		return m.Call
	}
	return nil
}

func (m *OptionItem) GetPut() *SecurityStaticInfo {
	if m != nil {
		return m.Put
	}
	return nil
}

type OptionChain struct {
	StrikeTime           *string       `protobuf:"bytes,1,req,name=strikeTime" json:"strikeTime,omitempty"`
	Option               []*OptionItem `protobuf:"bytes,2,rep,name=option" json:"option,omitempty"`
	StrikeTimestamp      *float64      `protobuf:"fixed64,3,opt,name=strikeTimestamp" json:"strikeTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OptionChain) Reset()         { *m = OptionChain{} }
func (m *OptionChain) String() string { return proto.CompactTextString(m) }
func (*OptionChain) ProtoMessage()    {}
func (*OptionChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{2}
}

func (m *OptionChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionChain.Unmarshal(m, b)
}
func (m *OptionChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionChain.Marshal(b, m, deterministic)
}
func (m *OptionChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionChain.Merge(m, src)
}
func (m *OptionChain) XXX_Size() int {
	return xxx_messageInfo_OptionChain.Size(m)
}
func (m *OptionChain) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionChain.DiscardUnknown(m)
}

var xxx_messageInfo_OptionChain proto.InternalMessageInfo

func (m *OptionChain) GetStrikeTime() string {
	if m != nil && m.StrikeTime != nil {
		return *m.StrikeTime
	}
	return ""
}

func (m *OptionChain) GetOption() []*OptionItem {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *OptionChain) GetStrikeTimestamp() float64 {
	if m != nil && m.StrikeTimestamp != nil {
		return *m.StrikeTimestamp
	}
	return 0
}

type S2C struct {
	OptionChain          []*OptionChain `protobuf:"bytes,1,rep,name=optionChain" json:"optionChain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{3}
}

func (m *S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C.Unmarshal(m, b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return xxx_messageInfo_S2C.Size(m)
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetOptionChain() []*OptionChain {
	if m != nil {
		return m.OptionChain
	}
	return nil
}

type Request struct {
	C2S                  *C2S     `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType              *int32   `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg               *string  `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
	ErrCode              *int32   `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	S2C                  *S2C     `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a5ab2b53e1bbfe, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil && m.RetMsg != nil {
		return *m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterEnum("Qot_GetOptionChain.OptionCondType", OptionCondType_name, OptionCondType_value)
	proto.RegisterType((*C2S)(nil), "Qot_GetOptionChain.C2S")
	proto.RegisterType((*OptionItem)(nil), "Qot_GetOptionChain.OptionItem")
	proto.RegisterType((*OptionChain)(nil), "Qot_GetOptionChain.OptionChain")
	proto.RegisterType((*S2C)(nil), "Qot_GetOptionChain.S2C")
	proto.RegisterType((*Request)(nil), "Qot_GetOptionChain.Request")
	proto.RegisterType((*Response)(nil), "Qot_GetOptionChain.Response")
}

func init() { proto.RegisterFile("Qot_GetOptionChain.proto", fileDescriptor_66a5ab2b53e1bbfe) }

var fileDescriptor_66a5ab2b53e1bbfe = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xfd, 0xd6, 0x76, 0x9a, 0x2f, 0x13, 0x04, 0xd1, 0x0a, 0xca, 0x12, 0xa1, 0x60, 0xf9, 0x64,
	0x2a, 0x51, 0x45, 0xab, 0x8a, 0x03, 0x37, 0xe4, 0x03, 0xe4, 0x80, 0x2a, 0xd6, 0x45, 0x1c, 0xab,
	0xd4, 0x5e, 0xda, 0x55, 0xeb, 0x5d, 0xb3, 0x3b, 0x51, 0xd5, 0x5f, 0xc0, 0x91, 0x1f, 0xc0, 0x9f,
	0x45, 0xbb, 0x75, 0xb0, 0x09, 0x41, 0xdc, 0x3c, 0xef, 0xbd, 0x99, 0x79, 0x3b, 0xcf, 0xc0, 0x3e,
	0x1a, 0x3c, 0x7f, 0x27, 0xf1, 0xb4, 0x45, 0x65, 0x74, 0x71, 0xb5, 0x56, 0xfa, 0xb8, 0xb5, 0x06,
	0x0d, 0xa5, 0x7f, 0x32, 0xf3, 0x07, 0x85, 0x69, 0x1a, 0xd3, 0x29, 0xe6, 0x33, 0xaf, 0x18, 0x22,
	0xd9, 0x0f, 0x02, 0x71, 0xc1, 0x4b, 0x7a, 0x04, 0x23, 0x73, 0xab, 0xa5, 0x65, 0x24, 0x8d, 0xf2,
	0x29, 0x7f, 0x7c, 0x3c, 0x50, 0x96, 0xb2, 0xda, 0x58, 0x85, 0x77, 0xe2, 0x5e, 0x42, 0x29, 0x24,
	0x78, 0xd7, 0x4a, 0x16, 0xa5, 0x24, 0x1f, 0x89, 0xf0, 0x4d, 0x9f, 0xc3, 0xa4, 0x32, 0xba, 0x56,
	0x7e, 0x33, 0x8b, 0x03, 0xd1, 0x03, 0x9e, 0xbd, 0x90, 0x97, 0x4a, 0x9f, 0xa9, 0x46, 0xb2, 0x24,
	0x8d, 0xf2, 0x89, 0xe8, 0x01, 0xca, 0x60, 0x2c, 0x75, 0x1d, 0xb8, 0x51, 0xe0, 0xb6, 0x65, 0x66,
	0x01, 0xee, 0x1f, 0xb3, 0x42, 0xd9, 0x50, 0x0e, 0x49, 0xb5, 0xbe, 0xb9, 0x61, 0x24, 0x25, 0xf9,
	0x94, 0x2f, 0xf6, 0x59, 0x2c, 0x71, 0x8d, 0xaa, 0x5a, 0xe9, 0x2f, 0x46, 0x04, 0x2d, 0x5d, 0x42,
	0xdc, 0x6e, 0x30, 0x58, 0xfd, 0x77, 0x8b, 0x97, 0x66, 0xdf, 0x09, 0x4c, 0x07, 0x17, 0xa4, 0x0b,
	0x00, 0x87, 0x56, 0x5d, 0xcb, 0x60, 0x90, 0x04, 0x83, 0x03, 0x84, 0xbe, 0x86, 0x03, 0x13, 0xe4,
	0x2c, 0x4a, 0xe3, 0x5f, 0x4b, 0x76, 0x02, 0xea, 0x5f, 0x21, 0x3a, 0x35, 0xcd, 0xe1, 0x51, 0x3f,
	0xc5, 0xe1, 0xba, 0x69, 0xc3, 0xdd, 0x88, 0xd8, 0x85, 0xb3, 0xf7, 0x10, 0x97, 0xbc, 0xa0, 0x6f,
	0x61, 0x6a, 0xfa, 0x91, 0x8c, 0x84, 0x6d, 0x2f, 0xfe, 0xbe, 0x2d, 0x7c, 0x8b, 0x61, 0x4f, 0x76,
	0x02, 0x63, 0x21, 0xbf, 0x6e, 0xa4, 0x43, 0xfa, 0x12, 0xe2, 0x8a, 0xbb, 0x2e, 0xee, 0xa7, 0xfb,
	0xa6, 0x14, 0xbc, 0x14, 0x5e, 0x93, 0x7d, 0x23, 0xf0, 0xbf, 0x90, 0xae, 0x35, 0xda, 0x49, 0xba,
	0x80, 0xb1, 0x95, 0x78, 0xe6, 0xf3, 0xf7, 0xbd, 0xa3, 0x37, 0xc9, 0xab, 0x93, 0xe5, 0x52, 0x6c,
	0x41, 0x7a, 0x08, 0x07, 0x56, 0xe2, 0x07, 0x77, 0x19, 0x6e, 0x3e, 0x11, 0x5d, 0x15, 0x42, 0xb6,
	0xb6, 0x30, 0xb5, 0xec, 0x7e, 0x8f, 0x6d, 0xe9, 0x9d, 0x38, 0x5e, 0xb1, 0x24, 0x44, 0xb4, 0xd7,
	0x49, 0xc9, 0x0b, 0xe1, 0x35, 0x47, 0x17, 0xf0, 0xb0, 0xc3, 0x8d, 0xae, 0xc3, 0xba, 0x67, 0xf0,
	0xe4, 0x77, 0xe4, 0xfc, 0x93, 0xbe, 0xd6, 0xe6, 0x76, 0xf6, 0xdf, 0x1e, 0xea, 0xb3, 0xc2, 0xab,
	0x95, 0x9e, 0x11, 0x3a, 0x87, 0xc3, 0x1d, 0xea, 0x74, 0x83, 0x4e, 0xd5, 0x72, 0x16, 0xfd, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x0a, 0xa2, 0x34, 0xd3, 0x60, 0x03, 0x00, 0x00,
}
